### ISSUE TITLE
which is the right trunk entity to use?

### ISSUE THREAD

**Issue by pilot1981** [audiconnect/audi_connect_ha#103]
Hi,
I need to have state of trunk door, but I found various doors states in my integration:

binary_sensor.audi_trunk
assumed_state: true
device_class: door

binary_sensor.audi_trunk_lock
assumed_state: true
device_class: lock

sensor.audi_doors_trunk_state
assumed_state: true

I tried to compare history of these entities, but they seems different...I don't understand the difference between these entitites...

**Comment by Jean-Jerrre** [comment]
> binary_sensor.audi_trunk assumed_state: true device_class: door
this return the state of the trunk (closed or open)
> binary_sensor.audi_trunk_lock assumed_state: true device_class: lock
this returns the state of the trunk's lock (locked or unlocked)
> sensor.audi_doors_trunk_state assumed_state: true
this returns the state of all car doors and the trunk. If one (or more) door or the trunk is open it return "open". If one door (or more) or the trunk is unlocked, it returns "unlocked".  If all doors and the trunk are locked, it returns "locked".

**Comment by coreywillwhat** [comment]
questions were answered. Closing issue.
