### ISSUE TITLE
Error setting up entry ***@*** for audiconnect

### ISSUE THREAD

**Issue by cgilis** [audiconnect/audi_connect_ha#107]
Just started with HA, so I'm a newbie, how can I fix this?
Don't know what the S-PIN is, is that the four digits from the audi app?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/audiconnect/audi_services.py:257
Integration: Audi Connect
First occurred: 15:07:58 (1 occurrences)
Last logged: 15:07:58

Error setting up entry ***@*** for audiconnect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/audiconnect/__init__.py", line 106, in async_setup_entry
    return await data.update(utcnow())
  File "/config/custom_components/audiconnect/audi_account.py", line 162, in update
    if not await self.connection.update(None):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 113, in update
    vehicles_response = await self._audi_service.get_vehicle_information()
  File "/config/custom_components/audiconnect/audi_services.py", line 257, in get_vehicle_information
    raise Exception("Invalid json in get_vehicle_information")
Exception: Invalid json in get_vehicle_information

**Comment by chemgeek** [comment]
The integration appears to be broken.

**Comment by oskretc** [comment]
same here. seem like Audi has changed something again

**Comment by derhappy** [comment]
Since yesterday morning (CET) the app is giving me a hard time (really need the heating in the morning). 
The integration on the other hand is working fine. HA was updated to core_2021.12.9 yesterday noon. Only some warnings about unavailable vehicle location every now and then, but overall the position is tracked.

**Comment by cgilis** [comment]
It's working now, did nothing.. :-)

**Comment by chemgeek** [comment]
For some reason, I reloaded the integration and now all my battery and charging data is gone.  Went from 24 to 16 entities.

**Comment by chemgeek** [comment]
Reloaded again and worked.  Must have been on Audi’s side

**Comment by shemeel** [comment]
i tried reload - did not work, deleted and now unable to set it up Saying invalid credentials

**Comment by coreywillwhat** [comment]
as part of clean up efforts we're closing stale issues.
please open a new issue if this problem is still occurring.
