### ISSUE TITLE
Service 'refresh_vehicle_data': API error. 'refresh_data' works but does not update

### ISSUE THREAD

**Issue by Rookie-Ron** [audiconnect/audi_connect_ha#108]
Using HA core-2021.12.7 I activated the audiconnect service to regularly update the data, using the VIN.
Contrary the description on this GitHub' site only service 'audiconnect.refresh_data' replies with data. I used NodeRed to verify response, which is a Unix timestamp, nicely updating when I call the service:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/77362566/149366083-61b75b1d-e8a7-45a2-a6bc-c028c41498b3.png">

The node itself is set up like this:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/77362566/149366255-209a3a43-a8d0-4548-90d3-1bcb91c63092.png">

When I created a LoveLace card, like the one on 'GitHub', it worked fine for the first day. But since two days no updating takes place anymore, with my HA Log showing the following:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/77362566/149366678-c7a0004a-0174-4b92-9a38-4992831aff0a.png">

Any idea whether this is a bug or suggestions for a different setup?
Moreover: is 'refresh_vehicle_data' deprecated or changed?

**Comment by oskretc** [comment]
Probably related to #107

**Comment by wigster** [comment]
Just wanted to bump this -- as of 1.0.0 this is still some kind of problem. The docs say that the service is audiconnect.refresh_vehicle_data, but this fails. audiconnect.refresh_data does work, but it is unclear to me if it actually does anything (last update time is not changing). 

The Spook integration monitoring the configuration is complaining that the audiconnect.refresh_data service does not exist.

**Comment by coreywillwhat** [comment]
> Just wanted to bump this -- as of 1.0.0 this is still some kind of problem. The docs say that the service is audiconnect.refresh_vehicle_data, but this fails. audiconnect.refresh_data does work, but it is unclear to me if it actually does anything (last update time is not changing).
> 
> The Spook integration monitoring the configuration is complaining that the audiconnect.refresh_data service does not exist.

`refresh_cloud_data` will update data from the cloud, but as you noted, it will not force a vehicle refresh. It only pulls the latest data that the cloud received when the vehicle last 'checked-in'. `Last_update` reflects the last time the vehicle checked-in.

#330 is for `refresh_vehicle_data` issue catch all.

Closing this issue but please let me know if I'm missing another issue in here.
