### ISSUE TITLE
Audi sometimes lost connection

### ISSUE THREAD

**Issue by dnl0319** [audiconnect/audi_connect_ha#109]
Hello everyone,

I have the problem that after some time the integration lose the connection to the car. Does someone known why this happens?

This is what it looks like:
![image](https://user-images.githubusercontent.com/61114433/150648946-82b57921-d3dc-4ff5-97f1-75932c520aaf.jpeg)
![image](https://user-images.githubusercontent.com/61114433/150648910-fb95b3b9-fdeb-41d3-acec-a715f50e69dd.png)
![image](https://user-images.githubusercontent.com/61114433/150648914-975a3daa-ff47-41f8-b0be-49ceecd8d4bc.png)

**Comment by t0bias-r** [comment]
I see similar issues

**Comment by chemgeek** [comment]
I have the same issue

**Comment by titiviking** [comment]
Issue is referenced here: https://github.com/davidgiga1993/AudiAPI/issues/13#issuecomment-1024899210

I don't have the required knowledge to change the code... can anyone have a look and give it a go ?

should be somewhere around here I guess:
`        # Now parse the html body and extract the target url, csfr token and other required parameters
        html = BeautifulSoup(page_reply, "html.parser")
        form_tag = html.find("form")

        form_inputs = html.find_all("input", attrs={"type": "hidden"})
        for form_input in form_inputs:
            name = form_input.get("name")
            form_data[name] = form_input.get("value")`

**Comment by titiviking** [comment]
Yep, thanks a lot. Does it for me. ;-)

**Comment by HaxxHaris** [comment]
Same here, since yesterday I get this error message.

Tested removing the integration and uploading it again, but it is not possible to set it up hmm.

Login to Audi service failed: 'NoneType' object has no attribute 'get'
18:11:34 – (ERROR) Audi Connect (custom integration)
Login to Audi service failed, trying again in 10 seconds
18:11:23 – (ERROR) Audi Connect (custom integration) - message first occurred at 18:11:13 and shows up 2 times

**Comment by t0bias-r** [comment]
> Same here, since yesterday I get this error message.
> 
> Tested removing the integration and uploading it again, but it is not possible to set it up hmm.
> 
> Login to Audi service failed: 'NoneType' object has no attribute 'get' 18:11:34 – (ERROR) Audi Connect (custom integration) Login to Audi service failed, trying again in 10 seconds 18:11:23 – (ERROR) Audi Connect (custom integration) - message first occurred at 18:11:13 and shows up 2 times

You have to apply this PR #110

**Comment by HaxxHaris** [comment]
> 

Thanks  t0bias-r it worked!
Do not understand how I could miss your post

**Comment by titiviking** [comment]
I talked too soon I guess... I'm still facing issues...

`ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle status report of WAXXXXXXXXXX005XXX: Cannot connect to host fal-3a.prd.eu.dp.vwg-connect.com:443 ssl:default [Try again]`
