### ISSUE TITLE
Feature request - Align implementation with Skoda Connect

### ISSUE THREAD

**Issue by titiviking** [audiconnect/audi_connect_ha#117]
It seems that VW Group is using same API format for the different brands they support.
Skoda Connect (for homeassistant) seem to have a quite mature implementation with a wide range of flexibility.
They are however lacking time and knowledge to progress efficiently.

Using the knowledge of this integration and its develper, a common integration, supportig multiple brnads could see the light of day.

https://github.com/lendy007/homeassistant-skodaconnect/issues/104

**Comment by cdnninja** [comment]
This may be something for us to look at in the future.
