### ISSUE TITLE
Audi Q4 etron

### ISSUE THREAD

**Issue by WimBre** [audiconnect/audi_connect_ha#130]
Hi, 

Can this also be used for reading information from the Audi Q4 etron?

I can't see much information in the My Audi app on my iPhone. Just the battery % and range.

**Comment by bavala3010** [comment]
What exactly is your question? Did you install this custom integration in Home Assistant and are you missing information in Home Assistant?

**Comment by BUGgs** [comment]
Hi,
I have also a q4 etron, and no data are available really, in particular regarding battery status…
As you can see in the attached screen capture.
![FB98A2A7-B279-48CE-BFDF-079A672887E6](https://user-images.githubusercontent.com/1854598/159064511-2ed0ae5e-0ee7-4717-bddd-39d4ed67cfd5.jpeg)

thanks !

**Comment by WimBre** [comment]
> What exactly is your question? Did you install this custom integration in Home Assistant and are you missing information in Home Assistant?

I have not yet installed this plugin because I first want to know whether this would also work with an Audi Q4.

In the "Myaudi" app I can only manage the pre-heating and information about battery %.

I was curious if installing this plugin would open up more options.

**Comment by KoenDTS** [comment]
> Hi, I have also a q4 etron, and no data are available really, in particular regarding battery status… As you can see in the attached screen capture. ![FB98A2A7-B279-48CE-BFDF-079A672887E6](https://user-images.githubusercontent.com/1854598/159064511-2ed0ae5e-0ee7-4717-bddd-39d4ed67cfd5.jpeg)
> 
> thanks !

I see exactly the same for my Q4. I hoped to be able to start and stop the charging via HA, however, not successful so far. Is this issue model related to the Q4 specifically? Is the start and stop charging service working the Audi fat e-tron? 

Thanks in advance!

**Comment by mpredfearn** [comment]
@KoenDTS I have a 2019 "fat" e-tron - yes the timer charging service works for me and I am able to change timer mode to immediate charging or timer charging (same as the options available in the Audi app). I can't "stop" charging - the car seems to accept, but ignore, that command. But there is no such command in the Audi app so that's not particularly surprising.

**Comment by andig** [comment]
Afaikt the Q4/eTron works a bit different. You cannot use VW tokens or https://mbboauth-1d.prd.ece.vwg-connect.com:

Instead:
- get IDK token in the usual way, but use etron client ID (`f4d0934f-32bf-4ce4-b3c4-699a7049ad26@apps_vw-dilab_com`)
- exchange IDK token AAZS token using https://aazsproxy-service.apps.emea.vwapps.io/token
- use AAZS token to retrieve list of vehicles via GraphQL from https://app-api.live-my.audi.com/vgql/v1/graphql
- continue with IDK token at https://mobileapi.apps.emea.vwapps.io

You will not get start/stop charging support.

**Comment by michaelhomeassistant** [comment]
No Information in HA. Only 2 entitäten.

**Comment by ronaldwigman** [comment]
> Afaikt the Q4/eTron works a bit different. You cannot use VW tokens or https://mbboauth-1d.prd.ece.vwg-connect.com:
> 
> Instead:
> 
> * get IDK token in the usual way, but use etron client ID (`f4d0934f-32bf-4ce4-b3c4-699a7049ad26@apps_vw-dilab_com`)
> * exchange IDK token AAZS token using https://aazsproxy-service.apps.emea.vwapps.io/token
> * use AAZS token to retrieve list of vehicles via GraphQL from https://app-api.live-my.audi.com/vgql/v1/graphql
> * continue with IDK token at https://mobileapi.apps.emea.vwapps.io
> 
> Electric range and SoC are available. You will not get start/stop charging support or odometer.

Does this mean that the current HACS integration needs to be adapted? If I understand correctly, that is using the VW tokens

**Comment by karliwalti** [comment]
Audi is rolling out the MMI software update since a month or so. More and more features are available now. 
Had anybody with this Q4 update tried to implement above routine and check which features are available?

**Comment by coreywillwhat** [comment]
please continue any conversations for Q4 issues on #207 which is active.
Closing this issue.
