### ISSUE TITLE
Feature Request: Reload from UI

### ISSUE THREAD

**Issue by itchensen** [audiconnect/audi_connect_ha#142]
I would love to see a "reload from UI" option in the future.

In my case, the integration often "crashes" on HA restart - in the integration overview I find something like: Error during setup  -please see logs
In this case, a restart of HA is enough to get it running again. I think, a reload from UI button would do the same and saves the overhead.

Thank you guys for taking this point into the backlog, as I don't have the neccessary skills yet.

Running audiconnect in version "2021.1.1" and HA in 2022.6.5

**Comment by cdnninja** [comment]
This exists in the native home assistant interface.  audi connect doesn't add this but rather the actual platform has it built in.  Closing due to age and that this already exists.
