### ISSUE TITLE
"Invalid credentials" again

### ISSUE THREAD

**Issue by d96moe** [audiconnect/audi_connect_ha#147]
HA integration stopped working for the last couple of weeks, tried to remove and re-add and now I only get "invalid credentials".

Latest versions of HA and audi_connect_ha

Location: Sweden
Credentials works in Audi web and Android app.

**Comment by N3rdix** [comment]
Similar behaviour with slightly different error message (despite the fact the integration does not work with the new Q4 e-Tron):

```
Login to Audi service failed: 'access_token'
```

Location: Germany

**Comment by Segran** [comment]
Same here….

**Comment by dmelliott20** [comment]
Same here again

**Comment by duckend** [comment]
The fix is ready in the wings here.. [https://github.com/arjenvrh/audi_connect_ha/pull/143#issue-1271721558](url)

**Comment by bartpaeleman** [comment]
the link that @duckend posted shows no content here. What is the fix, and can we maybe update on our end until the merge is done and an update is available through the HACS channel?

**Comment by Segran** [comment]
The fix works! It's only 5 lines of code that needs to be  modified - get the code in pull request #143. Or wait for an updated release...

**Comment by bartpaeleman** [comment]
Fix working fine here too after replacing the 2 files:

![image](https://user-images.githubusercontent.com/772458/176451177-e901919a-f9ec-4ed5-94b7-196b74b0b6aa.png)

**Comment by brettonw** [comment]
It sort of looks like this particular integration is not being actively supported. I also pulled from the "fixed" fork, but it's hard to call this all good. This component is the number one source of errors in my logs, and it sure looks like the Audi connect interface itself is very flakey.

**Comment by damienheiser** [comment]
> The fix is ready in the wings here.. [https://github.com/arjenvrh/audi_connect_ha/pull/143#issue-1271721558](url)

HELLA~~~~

**Comment by Segran** [comment]
Solved
