### ISSUE TITLE
Feature Request: isMoving as attribute

### ISSUE THREAD

**Issue by ThomPre99** [audiconnect/audi_connect_ha#148]
Hi all,

I used the iobroker ioBroker.vw-connect adapter with the attribute "isMoving". This attribute describes, if the car isMoving (=true) or not (=false). This is a nice Feature an I used it in automations. Now I change to home assistant and i miss this attribute.

Is it possible to implement this attribute in the HA-Integration?

In the iobroker-adapter in the file main.js the code is (starts at line 3622):
...
                                    if (resp.statusCode === 204) {
                                        this.setState(vin + ".position.isMoving", true, true);
                                        resolve();
                                        return;
                                    } else {
                                        this.setState(vin + ".position.isMoving", false, true);
                                    }
                                    if (body && body.storedPositionResponse && body.storedPositionResponse.parkingTimeUTC) {
                                        body.storedPositionResponse.position.parkingTimeUTC = body.storedPositionResponse.parkingTimeUTC;
                                    }
                                })
                                .catch((error) => {
                                    this.log.error(error);
                                });
                        }
...

Thanks a lot, gerat work und greets
Thomas

**Comment by robleeskyuk** [comment]
+1 for this feature please
