### ISSUE TITLE
How to use this package in China?

### ISSUE THREAD

**Issue by Chare-Dream** [audiconnect/audi_connect_ha#153]
In China, Audi connect logs in using the mobile phone number, but when I enter the mobile phone number in username, it shows INVALID.

**Comment by RichardTHF** [comment]
Yeah, same issue. 

Audi CN only allows for phone numbers for the login, when logging in I get the error "Username invalid". 

I have had a look through the code and can't see where it is doing validation against a specific string type? if I could have any pointers to where that validation is done I am happy to make my own branch to get it working in CN.

**Comment by casdr** [comment]
@RichardTHF @Chare-Dream could you try changing this line locally? https://github.com/arjenvrh/audi_connect_ha/blob/0c0eba5ecf18b14af67c7f65ff94f3014fbf3ab0/custom_components/audiconnect/config_flow.py#L59

To:

```
                    username=self._username,
```
