### ISSUE TITLE
Missing SOC and others

### ISSUE THREAD

**Issue by tomasenskede** [audiconnect/audi_connect_ha#154]
![image](https://user-images.githubusercontent.com/32595351/190490986-f4024565-c9f7-471f-be64-ba6fd7194f5a.png)
Can I get more information from my car?

**Comment by kjbu** [comment]
Maybe give the user more access in your Audi account?

**Comment by Kolbi** [comment]
Should be fixed, please check and close the issue.

**Comment by coreywillwhat** [comment]
This issue is present in #207 and #338 . Closing this as duplicate
