### ISSUE TITLE
Audi e-Tron 55, 2019 start_timed_charger works, but not start_charger

### ISSUE THREAD

**Issue by woopstar** [audiconnect/audi_connect_ha#159]
Hi,

On my Audi e-Tron 55 from 2019, I can successfully send a start_timed_charger to the car. It will then convert and stop charging and instead be in the timed mode.

But I am unable to revert to charge immediately. When I send a start_charger, nothing happens.

How do you switch off the timed charger/revert to charge immediately?

It is available in the API, and I have no problems reverting back the mode in the MyAudi App.

What information can I provide to help debug this issue?

**Comment by woopstar** [comment]
Found the issue.

https://github.com/arjenvrh/audi_connect_ha/pull/137 makes it stop working on my e-Tron 55 from 2019.

**Comment by Jsnijders232** [comment]
Hi, 

For my e-Tron 55 from 2019 I have a similar, but slightly different problem. start_timed_charger works, start_charger works (after the above fix from woopstar), but the stop_charger comment does not do anything. 

any ideas?

**Comment by woopstar** [comment]
> For my e-Tron 55 from 2019 I have a similar, but slightly different problem. start_timed_charger works, start_charger works (after the above fix from woopstar), but the stop_charger comment does not do anything.

stop_charger is not supported. What you need to do is to use the timed charger to start/stop the charger. There is a good description of how to do it here at Reddit: https://www.reddit.com/r/homeassistant/comments/t91ivp/comment/hzu00yr/

**Comment by gorstj** [comment]
How do I revert #137 from my copy of the plugin from home assistant
(I can't get it to start immediate charge e-tron 55 like woopstar)

**Comment by woopstar** [comment]
> How do I revert #137 from my copy of the plugin from home assistant
> (I can't get it to start immediate charge e-tron 55 like woopstar)

When you have added the integration in HA, ssh into the machine, go to /config/custom_components/audiconnect_ha and change the file back from what it was changed to in the PR. That was what I did.
