### ISSUE TITLE
Updated the new version just now, the whole integration stopped working

### ISSUE THREAD

**Issue by terppatyyppi** [audiconnect/audi_connect_ha#161]
Previous version worked perfectly. Now this happens upon restart (log):
Logger: homeassistant.setup
Source: setup.py:192
Setup failed for custom integration audiconnect: Unable to import component: cannot import name '_CONF_UNIT_SYSTEM_US_CUSTOMARY' from 'homeassistant.util.unit_system' (/usr/src/homeassistant/homeassistant/util/unit_system.py)

Also the integration re-download fails now.

Version: 7ff41b7

**Comment by shuntfield** [comment]
Same Here - looking to revert back.

**Comment by synack666** [comment]
Same here but the App on mobile dont work too, looks like problem on audi side.

**Comment by terppatyyppi** [comment]
Yes, now when trying, also the APP is not working. However, the integration still worked today fine with the previous version. Is there a way to revert back?

**Comment by synack666** [comment]
Time: 09:53 DE
it works again, seems to have been a stupid temporal connection, my upgrade and a problem at audi

**Comment by derhappy** [comment]
App is still down for me (DE, 10:00 local). Fahrzeugstatus konnte nicht abgerufen werden.
Software still is not their strong side.

**Comment by shuntfield** [comment]
Agree that Audi must be down, I cannot update from the App either.

Will wait before attempting revert.

**Comment by shuntfield** [comment]
> Software still is not their strong side.
🤣

**Comment by terppatyyppi** [comment]
I still get the same error. Yes, SW is not their thing, amongst other things,... 
The APP also started showing Fuel tank level (instead of charge level) for my EV some days ago :)

**Comment by terppatyyppi** [comment]
Still does not work in Finland.

**Comment by simonepittis** [comment]
problem on VW side:
This error originated from a custom integration.
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:94
Integration: Audi Connect

Login to Audi service failed: 404, message='Not Found', url=URL('https://idkproxy-service.apps.emea.vwapps.io/v1/emea/openid-configuration')

and:
404 Not Found: Requested route ('idkproxy-service.apps.emea.vwapps.io') does not exist.

Somthing wrong in the Server side routing config

**Comment by simonepittis** [comment]
> problem on VW side: This error originated from a custom integration. Logger: custom_components.audiconnect.audi_connect_account Source: custom_components/audiconnect/audi_connect_account.py:94 Integration: Audi Connect
> 
> Login to Audi service failed: 404, message='Not Found', url=URL('https://idkproxy-service.apps.emea.vwapps.io/v1/emea/openid-configuration')
> 
> and: 404 Not Found: Requested route ('idkproxy-service.apps.emea.vwapps.io') does not exist.
> 
> Somthing wrong in the Server side routing config

back online now :-)

**Comment by terppatyyppi** [comment]
Yes, the Audi APP seems to work again (mostly)...but the latest version of the integration still doesn't. Can anyone help with a rollback to the previous version, or is it not possible?

**Comment by shogun168** [comment]
Down for me too, app working just fine and previous version of this integratin was working too.

**Comment by terppatyyppi** [comment]
Got frustrated with this...wanted to try and rebuild it.
I was unable to delete the home assistant integration configuration (which was still not working), I selected delete from the drop-down list, nothing happens. It remains configured, so I just disabled the configuration, restarted home assistant and tried deleting again, nothing happened.
I then proceeded to remove the HACS integration and re-installed that.
Now when I try to configure this in home assistant, I get this: "Config flow could not be loaded: {"message":"Invalid handler specified"}"

So, not able to do anything for this now. The "old" configuration ghost is still there, as disabled. The newly downloaded integration won't allow configuration so I'm totally lost now.

**Comment by N3rdix** [comment]
Might be related to [this deprecation](https://developers.home-assistant.io/blog/2022/10/14/deprecate-unit-system) which has been handled with the latest PR here. 
I am facing the exact same error being still on 2022.10.5, but I'm not yet willing to update 2022.11 to see if this fixes the problem :-)

**Comment by lekdin** [comment]
New versio wordek shortly this weekend, now broken again and back to previous version which will load fine
dc92005
Downloaded version
7ff41b7
Available version

**Comment by rick-cross** [comment]
> New versio wordek shortly this weekend, now broken again and back to previous version which will load fine [dc92005](https://github.com/arjenvrh/audi_connect_ha/commit/dc920058be139a9ca006fe084185395e8d0cdbe8) Downloaded version [7ff41b7](https://github.com/arjenvrh/audi_connect_ha/commit/7ff41b717ac279385555a8f0376168d6322f3f30) Available version

Thanks for the tip. I updated today to the latest available and the functionality broke for me.
I manually downloaded the files from dc92005 that you linked above and moved that into the custom_components folder and its back to working normally.

**Comment by terppatyyppi** [comment]
Started working again yesterday for me too!

**Comment by pst51** [comment]
> Now when I try to configure this in home assistant, I get this: "Config flow could not be loaded: {"message":"Invalid handler specified"}"

Having the same issue here. Impossible to reinstall/reconfigure the audiconnect integration. Could you explain how dis you solve this issue ?

Thks

**Comment by terppatyyppi** [comment]
> Having the same issue here. 
> Impossible to reinstall/reconfigure the audiconnect integration. Could you explain how dis you solve this issue ?

Unfortunately I have no idea: after more than a week, I retried to configure and it just worked.
