### ISSUE TITLE
Access to charging power to be added to energy dashboard

### ISSUE THREAD

**Issue by Famas1978** [audiconnect/audi_connect_ha#164]
Hi

The apps works has it should be be but I would like to request for an update:
Can it be possible to have the charging power in real time to be able to make reporting on it and to add it into the energy dashboard?

Thanks in advance

**Comment by Kolbi** [comment]
I'm just thinking about this topic... it would be interesting for me either.

I think about:
If ENERGY_FLOW is on
230 V x 10 A x 2 x 0.5/1 (50/100%)=> 7360W or 3680W....

Or instead of ENERGY_FLOW use e_charging_mode = 'AC' or e_charging_state = 'charging'

Because the power we don't have as value?

**Comment by Kolbi** [comment]
I'll have a look into https://github.com/bramstroker/homeassistant-powercalc
