### ISSUE TITLE
ERROR update_vehicle_shortterm object has attribute

### ISSUE THREAD

**Issue by Segran** [audiconnect/audi_connect_ha#165]
Hi,
my log fills up constantly with the following error message:
2023-01-11 18:15:10.690 ERROR (MainThread) [custom_components.audiconnect.util] Unable to update vehicle data shortterm of WAUZZZZZZZZZZZZ: 'AudiConnectVehicle' object has no attribute 'update_vehicle_shortterm'

This is repeated every 30-35 seconds, so the log fills up pretty fast.

I have updated the integration in Home Assistant using HACS, and running Home Assistant core 2023.1.2 on Mac OS Ventura 12.6.2.

Anyone know what causes this?

**Comment by woopstar** [comment]
I commented out these lines in the code:

```
            # info = "shortterm"                                       
            # await self.call_update(self.update_vehicle_shortterm, 3)
            # info = "longterm"
            # await self.call_update(self.update_vehicle_longterm, 3)
```

found in `audi_connect_account.py`

**Comment by EivindH0** [comment]
> I commented out these lines in the code:
> 
> ```
>             # info = "shortterm"                                       
>             # await self.call_update(self.update_vehicle_shortterm, 3)
>             # info = "longterm"
>             # await self.call_update(self.update_vehicle_longterm, 3)
> ```
> 
> found in `audi_connect_account.py`

Thank you - this solved my error messages.
