### ISSUE TITLE
Implementing the card example

### ISSUE THREAD

**Issue by erdbeertoni** [audiconnect/audi_connect_ha#183]
First of all, sorry for my beginners question. 
I was able to install and connect my Audi to get the car values in my dashboard but I also tried to implement your cool card example. I already installed the two front end mods through HACS but then i stuck on the last mile here:
`The card uses the following code in ui-lovelace.yaml (or wherever your Dashboard is configured).`

Where do I have to put in this code to get these cool car graphic and values to my dashboard?

Thank you so much

**Comment by synack666** [comment]
new card with code:

type: picture-elements
elements:
  - type: icon
    icon: mdi:car-door
    entity: binary_sensor.audi_s4_avant_doors_lock
    tap_action: more_info
    style:
      color: black
      left: 10%
      top: 86%
  - type: state-label
    entity: binary_sensor.audi_s4_avant_doors_lock
    style:
      color: black
      left: 10%
      top: 95%
  - type: icon
    icon: hass:window-closed
    entity: binary_sensor.audi_s4_avant_windows
    tap_action: more_info
    style:
      color: black
      left: 50%
      top: 86%
  - type: state-label
    entity: binary_sensor.audi_s4_avant_windows
    style:
      color: black
      left: 50%
      top: 95%
  - type: icon
    icon: mdi:gas-station
    entity: sensor.audi_s4_avant_tank_level
    tap_action: more_info
    style:
      color: black
      left: 9%
      top: 16%
  - type: state-label
    entity: sensor.audi_s4_avant_tank_level
    style:
      color: black
      left: 10%
      top: 25%
  - type: state-label
    entity: sensor.audi_s4_avant_range
    style:
      color: black
      left: 10%
      top: 30%
  - type: state-icon
    entity: binary_sensor.audi_s4_avant_sun_roof
    tap_action: more_info
    style:
      color: black
      left: 30%
      top: 86%
  - type: state-label
    entity: binary_sensor.audi_s4_avant_sun_roof
    style:
      color: black
      left: 30%
      top: 95%
  - type: icon
    icon: mdi:oil
    entity: sensor.audi_s4_avant_oil_level
    tap_action: more_info
    style:
      color: black
      left: 90%
      top: 84%
  - type: state-label
    entity: sensor.audi_s4_avant_oil_level
    style:
      color: black
      left: 90%
      top: 90%
  - type: state-label
    entity: sensor.audi_s4_avant_oil_change_time
    style:
      color: black
      left: 90%
      top: 95%
  - type: icon
    icon: mdi:wrench
    entity: sensor.audi_s4_avant_service_inspection_time
    tap_action: more_info
    style:
      color: black
      left: 70%
      top: 86%
  - type: state-label
    entity: sensor.audi_s4_avant_service_inspection_time
    style:
      color: black
      left: 70%
      top: 95%
  - type: icon
    icon: mdi:speedometer
    entity: sensor.audi_s4_avant_mileage
    tap_action: more_info
    style:
      color: black
      left: 90%
      top: 16%
  - type: state-label
    entity: sensor.audi_s4_avant_mileage
    style:
      color: black
      left: 90%
      top: 25%
image: /local/s4.PNG


![grafik](https://github.com/arjenvrh/audi_connect_ha/assets/60230729/f9376bbd-ae42-4ff0-a1ee-025e2bdf46e9)
