### ISSUE TITLE
Login to Audi service failed

### ISSUE THREAD

**Issue by synack666** [audiconnect/audi_connect_ha#184]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

since yesterday it no longer wants, myaudi works the login but no data, app works.
does anyone else have this?

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:94
Integration: Audi Connect (documentation, issues)
First occurred: 8. Mai 2023 um 20:08:44 (183 occurrences)
Last logged: 06:29:27

Login to Audi service failed, trying again in 10 seconds
Login to Audi service failed: 'refresh_token'
Login to Audi service failed: 'client_id'

**Comment by LionelJeans** [comment]
The error occurs during config retrieval:
Login to Audi service failed: Cannot connect to host idkproxy-service.apps.emea.vwapps.io:443 ssl:default [Name or service not known]
openidcfg_url = "https://idkproxy-service.apps.{0}.vwapps.io/v1/{0}/openid-configuration".format("na" if self._country.upper() == "US" else "emea")
# get openId config
openidcfg_json = await self._api.request("GET", openidcfg_url, None)

**Comment by LCMilstein** [comment]
Hasn't been working for me all week either. I'm on 2023.5.3 and initially assumed Audi was offline, but the app is working again, just not the HA integration. Anyone work knowledge of the things able to help fix it?

**Comment by thorsten** [comment]
I have the same issues.

**Comment by LCMilstein** [comment]
This seems to happen whenever Audi releases a new update. Looking at the changes that re-enabled things last time, it appears we need specific date stamps and version and build numbers, which I think we can find most of without too much hassle, but then there are also changes to the numbers that make up the xqmauth_secret. I am *totally* clueless as to how @arjenvrh or others have been able to identify those in the past. Is there some sort of inspection to the APK we can do or is this more than even that (not that I'd know how to inspect the APK for this...)

**Comment by t0bias-r** [comment]
@LCMilstein see comment here: https://github.com/arjenvrh/audi_connect_ha/issues/169#issuecomment-1571420984
Not every app update contains breaking changes. Currently I think it's an Audi backend issue.

**Comment by t0bias-r** [comment]
> I am _totally_ clueless as to how @arjenvrh or others have been able to identify those in the past. Is there some sort of inspection to the APK we can do or is this more than even that (not that I'd know how to inspect the APK for this...)

I use a mix of different methods: some static analysis of the APK, but mostly runtime analysis of (decrypted) network traffic and analysis of how and when Andoird API calls are performed.

**Comment by synack666** [comment]
I have opened a ticket with Audi, also do not see any data under myAudi.de in the browser.

**Comment by pilot1981** [comment]
issue also here...

**Comment by asemev** [comment]
i also have the same problem, since roughly 3 months or so...

**Comment by LionelJeans** [comment]
it's been working again since just now

**Comment by t0bias-r** [comment]
The issue I have is present in the Audi app as well.
Since a few weeks, the problem exists from around 15:00 GMT to 0:00 GMT every day (what is 17:00 till 2:00 in my timezone).
I can see detailed logs when the problem starts and ends and it is the same error every day.

I'm using iOS and Audi app is up-to-date, of course.

see https://github.com/arjenvrh/audi_connect_ha/issues/169#issuecomment-1571420984
![grafik](https://github.com/arjenvrh/audi_connect_ha/assets/95424140/0e32ed7e-210b-41be-b829-a991534dddd6)

**Comment by synack666** [comment]
back again since yesterday

**Comment by thorsten** [comment]
It's working for me as well since today

**Comment by asemev** [comment]
also works for me now...
