### ISSUE TITLE
Only seeing 2 entities

### ISSUE THREAD

**Issue by mrasmith** [audiconnect/audi_connect_ha#185]
I'm after installing this integration for my E-tron using HACS but I only see two entities, lock.audi_e_tron_door_lock and sensor.audi_e_tron_model. I previously had it working a couple of months ago but had disabled it temporarily for unrelated reasons. Now it doesn't seem to work anymore, is there a solution ?

**Comment by moritzwiechers** [comment]
Same for me here. Do we need to change an api endpoint or sth. else?

**Comment by asemev** [comment]
Same here...

**Comment by casapesce** [comment]
me too, re-enabled after disabling it for 2 months for other reasons

**Comment by mrasmith** [comment]
Mine started working again!, I had to remove another user account so that there was only one (key user) and then reinstall on Home Assistant and it pulled in all entities again.

**Comment by casapesce** [comment]
> Mine started working again!, I had to remove another user account so that there was only one (key user) and then reinstall on Home Assistant and it pulled in all entities again.

Sorry could you explain it to me that I didn't understand well? :)
Tanks

**Comment by jlatvala** [comment]
Same problem here. Only two entities (lock.audi_e_tron_door_lock and sensor.audi_e_tron_model).

Only one user (key user) added to the car.
Didn't give S-PIN in the setup.

Audi Q4.

**Comment by leopold005** [comment]
Same here - Q4 etron.  I'd have expected to see at least how many miles were left in the battery or some such, but just having the lock status and the model of car is a bit pointless

**Comment by hstandaert** [comment]
+1 for Audi Q4.

**Comment by BobC76** [comment]
+1 for Audi Q4. 

I've resorted to https://github.com/tronity/homeassistant which has been able to get the data I wanted, so far, as long as the free account on tronity lasts.

Logs contain 

```
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:109
Integration: Audi Connect (documentation, issues)
First occurred: 15:44:33 (4 occurrences)
Last logged: 16:14:36

Unable to obtain the vehicle shortTerm tripdata of [VEHICLE_VIN]: 403, message='', url=URL('https://mal-1a.prd.ece.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/[VEHICLE_VIN]/tripdata/shortTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-07-24T16:14:33Z')

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:116
Integration: Audi Connect (documentation, issues)
First occurred: 15:14:30 (7 occurrences)
Last logged: 15:14:31

Unable to obtain the vehicle longTerm tripdata of [VEHICLE_VIN]: 403, message='', url=URL('https://mal-1a.prd.ece.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/[VEHICLE_VIN]/tripdata/longTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-07-24T15:44:30Z')
support_position set to False: 502
support_climater set to False: 403
support_charger set to False: 403
support_preheater set to False: 502
```

**Comment by Microclisma** [comment]
Same problem today after the update. Before it wasn't even working anymore, now I only see 2 entities. I have a single account on Audi connect. Tried reinstalling the addon, but no changes

**Comment by goetzpil** [comment]
+1

**Comment by HannesVo** [comment]
+1 Audi Q4

**Comment by stijn220** [comment]
+1

**Comment by moritzwiechers** [comment]
Hey,
I created a [fork](https://github.com/moritzwiechers/audi_connect_ha_q4) with some adjustments to get some data for my q4 etron. 
I don't know python or home-assistant integrations. I don't know why the "old" endpoint won't work, but I found one that works in some way (different data structure) and put it in my fork. For me (located in germany) it is working and I added battery soc, milage and range. 
You can add it via a custom repository.
Maybe some skilled python dev could use the informations to enhance it.

**Comment by Kolbi** [comment]
Should be fixed, please check and close the issue.
