### ISSUE TITLE
Hass 2023.8 position doesn't work anymore

### ISSUE THREAD

**Issue by Flashlab2** [audiconnect/audi_connect_ha#193]
Since the latest HA update I don't get location info any longer. This I can find in the log:

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:116
Integration: Audi Connect (documentation, issues)
First occurred: 14:18:34 (5 occurrences)
Last logged: 14:18:37

Unable to obtain the vehicle shortTerm tripdata of xxx: 403, message='', url=URL('https://mal-1a.prd.ece.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/xxx/tripdata/shortTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-08-03T13:48:33Z')
Unable to obtain the vehicle longTerm tripdata of xxx: 403, message='', url=URL('https://mal-1a.prd.ece.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/xxx/tripdata/longTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-08-03T13:48:34Z')
support_climater set to False: 403
support_charger set to False: 403
support_preheater set to False: 502

**Comment by rgcouto** [comment]
Same here!

**Comment by rhoddan** [comment]
same problem

**Comment by hssmith76** [comment]
Same here

**Comment by euri911** [comment]
one more with the issue.

**Comment by Heelderpeel** [comment]
Work arround:

in the audiconnect file: device_tracker.py Simple put a # for line 124 it looks like this:
# "device_type": "device_tracker",

**Comment by euri911** [comment]
Excellent, works like a charm :)

Thank you!

**Comment by muhkuh666** [comment]
Same here with 8.1 when will there be an update?

**Comment by muhkuh666** [comment]
> Work arround:
> 
> in the audiconnect file: device_tracker.py Simple put a # for line 124 it looks like this: **_# "device_type": "device_tracker",_**

where an how to find?

**Comment by Heelderpeel** [comment]
> > Work arround:
> > in the audiconnect file: device_tracker.py Simple put a # for line 124 it looks like this: **_# "device_type": "device_tracker",_**
> 
> where an how to find?

i use the Filebrowser addon from: https://github.com/alexbelgium/hassio-addons/tree/master/filebrowser
then search for audiconnect

**Comment by Heelderpeel** [comment]
> Same here with 8.1 when will there be an update?

on https://github.com/arjenvrh/audi_connect_ha
can you see the answer:

Maintainers Wanted
Due to time limitations this project is not actively maintained anymore. It will continue to work as long as Audi does not change the API again. However, I'm open to someone else taking the lead. If you would like to become a maintainer, please contact me.

**Comment by chichi1967** [comment]
To get location information back I also had to **remove my entry/account from the Audi integration and re-add it**, without doing so I got the 403 error message, while the other information came back directly after **#** in front of the **"device_type": "device_tracker",** lines in the files **device_tracker.py** and **entity_platform.py**.

**Comment by devslash0** [comment]
This issue is back. Position/location entity is missing.
