### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by Sammy990** [audiconnect/audi_connect_ha#196]
My working integration stopped working in the last couple of weeks. All sensors and devices became unavailable.

I decided to reinstall the plugin. The account is added successfully within the wizard, but No devices or entities are discovered.

Anyone else having the same issue?

**Comment by coreywillwhat** [comment]
See #191 .
Same boat as you. Still hasn't been figured out. I've tried the 'fixes' from #192 and #193 with no luck.
At this point i think we're just waiting/hoping some python dev with HA buys a newer Audi and wants the functionality :(

**Comment by cdnninja** [comment]
Is it working for you now?

**Comment by coreywillwhat** [comment]
Closing due to lack of response. My issue was resolved....my how far we've come. lol
