### ISSUE TITLE
issue custom_components.audiconnect.audi_connect_account

### ISSUE THREAD

**Issue by nelloshotz** [audiconnect/audi_connect_ha#210]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:429 
Integration: Audi Connect (documentation, issues) 
First occurred: 11:43:32 (4 occurrences) 
Last logged: 11:44:25

Unable to obtain the vehicle shortTerm tripdata of WAUZZZ4MXMD006639: 403, message='', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/WAUZZZ4MXMD006639/tripdata/shortTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-11-10T12:13:32Z')
Unable to obtain the vehicle longTerm tripdata of WAUZZZ4MXMD006639: 403, message='', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/WAUZZZ4MXMD006639/tripdata/longTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-11-10T12:13:32Z')
Unable to obtain the vehicle shortTerm tripdata of WAUZZZ4MXMD006639: 403, message='', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/WAUZZZ4MXMD006639/tripdata/shortTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-11-10T12:14:24Z')
Unable to obtain the vehicle longTerm tripdata of WAUZZZ4MXMD006639: 403, message='', url=URL('https://mal-3a.prd.eu.dp.vwg-connect.com/api/bs/tripstatistics/v1/vehicles/WAUZZZ4MXMD006639/tripdata/longTerm?type=list&from=1970-01-01T00:00:00Z&to=2023-11-10T12:14:25Z')

anyone can help me?? I set user, pass, spin

**Comment by Heelderpeel** [comment]
same problem for me.

**Comment by 1979SAJ** [comment]
The same problem for me.

**Comment by sytchi** [comment]
Same. Did anyone found an issue? Or someone know a solution/workaround?

**Comment by bartsmetdv** [comment]
It's an old issue.
The easiest workaround is to comment out the timestamp in the audi_connect_account.py file :

  ```
  async def update_vehicle_tripdata(self, kind: str):
        try:
            td_cur, td_rst = await self._audi_service.get_tripdata(self._vehicle.vin, kind)
            self._vehicle.state[kind.lower() + "_current"] = {
                "tripID": td_cur.tripID,
                "averageElectricEngineConsumption": td_cur.averageElectricEngineConsumption,
                "averageFuelConsumption": td_cur.averageFuelConsumption,
                "averageSpeed": td_cur.averageSpeed,
                "mileage": td_cur.mileage,
                "startMileage": td_cur.startMileage,
                "traveltime": td_cur.traveltime,
#                "timestamp": td_cur.timestamp,
                "overallMileage": td_cur.overallMileage,
            }
            self._vehicle.state[kind.lower() + "_reset"] = {
                "tripID": td_rst.tripID,
                "averageElectricEngineConsumption": td_rst.averageElectricEngineConsumption,
                "averageFuelConsumption": td_rst.averageFuelConsumption,
                "averageSpeed": td_rst.averageSpeed,
                "mileage": td_rst.mileage,
                "startMileage": td_rst.startMileage,
                "traveltime": td_rst.traveltime,
#                "timestamp": td_rst.timestamp,
                "overallMileage": td_rst.overallMileage,
            }
```
This makes the answer string below the limit of 254 chars.
There should of course be a more elegant way to solve this properly.

**Comment by Kolbi** [comment]
https://github.com/arjenvrh/audi_connect_ha/issues/226
