### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Ralf-Th** [audiconnect/audi_connect_ha#212]
Hello,
i installed this integration for my Q4, but after 3 days I now see setup error (Fehler beim Einrichten)
i reinstalled the integration, but all entities are not available.

**Comment by MisterTil** [comment]
Same here :/

**Comment by over40** [comment]
Same here :(

**Comment by over40** [comment]
It works again...

**Comment by Kolbi** [comment]
Should be fixed, please check and close the issue.
