### ISSUE TITLE
Unable to obtain the vehicle longTerm + shortTerm tripdata

### ISSUE THREAD

**Issue by Prash1407** [audiconnect/audi_connect_ha#226]
Got this in my logs and I think this request to the server could be removed?

```
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:429
Integration: Audi Connect ([documentation](https://github.com/arjenvrh/audi_connect_ha), [issues](https://github.com/arjenvrh/audi_connect_ha/issues))
First occurred: 23:37:25 (18 occurrences)
Last logged: 23:39:01

Unable to obtain the vehicle longTerm tripdata ...
```
```
Unable to obtain the vehicle shortTerm tripdata ...
```

I have found some possibly helpful source to resolve this issue:

https://github.com/TA2k/ioBroker.vw-connect/commit/1aecb8be4c4a6a239da2c974cd894de97eb55645#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916a

**Comment by Kolbi** [comment]
https://github.com/arjenvrh/audi_connect_ha/issues/210

**Comment by coreywillwhat** [comment]
Thanks for your interest in this information!
Unfortunately, This is known to not be working at the moment. With API change, the structure is different and needs to be adapted. Closing to capture all related under a catch all issue: #344
