### ISSUE TITLE
Errors in release 0332c1a (04.03.2024)

### ISSUE THREAD

**Issue by derhappy** [audiconnect/audi_connect_ha#247]
First of all, **thanks** to everybody who has been working quite hard the last days to bring the integration back to life!

In the current version I get the error below. I'm driving a e-tron 55.

```
Unable to obtain the vehicle status report of WAUZZZGE1NB0xxxxx: 'currentFuelLevel_pct'

Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 436, in update_vehicle_statusreport
    status = await self._audi_service.get_stored_vehicle_data(self._vehicle.vin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_services.py", line 190, in get_stored_vehicle_data
    return VehicleDataResponse(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_models.py", line 43, in __init__
    FuelStatus = data["fuelStatus"]["rangeStatus"]["value"]["primaryEngine"]["currentFuelLevel_pct"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'currentFuelLevel_pct'
```

**Comment by DivingUp** [comment]
please activate line 189 in audi_services.py and provide me with the logs from the HA log "Audi Data".
I no longer see any oil levels in the Audi API... either it is the vehicle or the API...thx

**Comment by t0bias-r** [comment]
@derhappy check the PR #249 or for testing that fork: https://github.com/t0bias-r/audi_connect_ha

**Comment by t0bias-r** [comment]
> please activate line 189 in audi_services.py and provide me with the logs from the HA log "Audi Data". I no longer see any oil levels in the Audi API... either it is the vehicle or the API...thx

@DivingUp Jedes Json Element hart kodiert auf Existenz zu überprüfen, in einer Variable zu speichern und anschließend hinzuzufügen, erscheint mit wenig Effektiv. Ich meins nur gut - deshalb die extra tryAppend Funktionen, die den Zeitstempel und den Wert auf Existenz überprüfen und ggf. hinzufügen. Was es gibt, wird hinzugefügt, das andere wird übersprungen und verursacht keinen Fehler. Des Weiteren ist es pro Sensor nur eine Codezeile.

**Comment by DivingUp** [comment]
> > please activate line 189 in audi_services.py and provide me with the logs from the HA log "Audi Data". I no longer see any oil levels in the Audi API... either it is the vehicle or the API...thx
> 
> @DivingUp Jedes Json Element hart kodiert auf Existenz zu überprüfen, in einer Variable zu speichern und anschließend hinzuzufügen, erscheint mit wenig Effektiv. Ich meins nur gut - deshalb die extra tryAppend Funktionen, die den Zeitstempel und den Wert auf Existenz überprüfen und ggf. hinzufügen. Was es gibt, wird hinzugefügt, das andere wird übersprungen und verursacht keinen Fehler. Des Weiteren ist es pro Sensor nur eine Codezeile.

vollkommen richtig, war auch nicht glücklich mit der vorgehensweise, wurde nur so per merge übernommen und wollte dann nicht im nächsten update einfach deinen code kopieren.
so, ist der beste weg...
in der dashboard.py ist adblue doppelt drin... sonst gern rein damit und dann haben wir alle eine neue basis-version, mit der alle gleich weiter arbeiten können.
würde noch empfehlen, den möglichen log-output in der audi_service.py line 189 zu übernehmen... so haben wir die chance, einfach von den usern an daten zu bekommen...

**Comment by eskholm** [comment]
> > please activate line 189 in audi_services.py and provide me with the logs from the HA log "Audi Data". I no longer see any oil levels in the Audi API... either it is the vehicle or the API...thx
> 
> @DivingUp Jedes Json Element hart kodiert auf Existenz zu überprüfen, in einer Variable zu speichern und anschließend hinzuzufügen, erscheint mit wenig Effektiv. Ich meins nur gut - deshalb die extra tryAppend Funktionen, die den Zeitstempel und den Wert auf Existenz überprüfen und ggf. hinzufügen. Was es gibt, wird hinzugefügt, das andere wird übersprungen und verursacht keinen Fehler. Des Weiteren ist es pro Sensor nur eine Codezeile.

Could we keep the language english for everyones sanity? :)

**Comment by derhappy** [comment]
Thank you @t0bias-r! 
I can confirm the integration is running again with this PR. It feels like I have more entities than ever. Some I don't care about are unknown, like trip data. The charging data is not available which makes sense since the car is not plugged in.

The only sensor I'm missing is "sensor.audi_e_tron_sportback_climatisation_state"
I can not test the climatization call today. 

I'll keep the issue open in case you want to discuss something else. If there is no update, I will close it tomorrow if it's still open.

**Comment by Kolbi** [comment]
> > > please activate line 189 in audi_services.py and provide me with the logs from the HA log "Audi Data". I no longer see any oil levels in the Audi API... either it is the vehicle or the API...thx
> > 
> > 
> > @DivingUp Jedes Json Element hart kodiert auf Existenz zu überprüfen, in einer Variable zu speichern und anschließend hinzuzufügen, erscheint mit wenig Effektiv. Ich meins nur gut - deshalb die extra tryAppend Funktionen, die den Zeitstempel und den Wert auf Existenz überprüfen und ggf. hinzufügen. Was es gibt, wird hinzugefügt, das andere wird übersprungen und verursacht keinen Fehler. Des Weiteren ist es pro Sensor nur eine Codezeile.
> 
> vollkommen richtig, war auch nicht glücklich mit der vorgehensweise, wurde nur so per merge übernommen und wollte dann nicht im nächsten update einfach deinen code kopieren. so, ist der beste weg... in der dashboard.py ist adblue doppelt drin... sonst gern rein damit und dann haben wir alle eine neue basis-version, mit der alle gleich weiter arbeiten können. würde noch empfehlen, den möglichen log-output in der audi_service.py line 189 zu übernehmen... so haben wir die chance, einfach von den usern an daten zu bekommen...

Maybe a variable in the config_flow for easy activation for enduser?

**Comment by kevindebosscher** [comment]
New release solves all previous problems!
![IMG_4365](https://github.com/arjenvrh/audi_connect_ha/assets/23461848/f7332d92-f202-459e-b0c3-2d5cc1c56891)

**Comment by cdnninja** [comment]
> > > > please activate line 189 in audi_services.py and provide me with the logs from the HA log "Audi Data". I no longer see any oil levels in the Audi API... either it is the vehicle or the API...thx
> > > 
> > > 
> > > @DivingUp Jedes Json Element hart kodiert auf Existenz zu überprüfen, in einer Variable zu speichern und anschließend hinzuzufügen, erscheint mit wenig Effektiv. Ich meins nur gut - deshalb die extra tryAppend Funktionen, die den Zeitstempel und den Wert auf Existenz überprüfen und ggf. hinzufügen. Was es gibt, wird hinzugefügt, das andere wird übersprungen und verursacht keinen Fehler. Des Weiteren ist es pro Sensor nur eine Codezeile.
> > 
> > 
> > vollkommen richtig, war auch nicht glücklich mit der vorgehensweise, wurde nur so per merge übernommen und wollte dann nicht im nächsten update einfach deinen code kopieren. so, ist der beste weg... in der dashboard.py ist adblue doppelt drin... sonst gern rein damit und dann haben wir alle eine neue basis-version, mit der alle gleich weiter arbeiten können. würde noch empfehlen, den möglichen log-output in der audi_service.py line 189 zu übernehmen... so haben wir die chance, einfach von den usern an daten zu bekommen...
> 
> Maybe a variable in the config_flow for easy activation for enduser?

I created #252 this plus some debug lines should take care of?
