### ISSUE TITLE
Cant lock/unlock or start/stop preheater

### ISSUE THREAD

**Issue by wessa66** [audiconnect/audi_connect_ha#262]
Hi
I see this in the log when I try to start/stop Preheater and lock/unlock my Audi A4

----------------  FROM log below -------------------
This error originated from a custom integration.

Logger: custom_components.audiconnect.util
Source: custom_components/audiconnect/util.py:25
integration: Audi Connect (documentation, issues)
First occurred: 8:19:29 AM (1 occurrences)
Last logged: 8:19:29 AM

Unable to start pre-heater of vehicle [VIN NUMBER REMOVED] object of type 'NoneType' has no len()

**Comment by t0bias-r** [comment]
I think that it is related to the new Audi API that is not yet integrated for these actions.

**Comment by Kolbi** [comment]
I try to collect the status of (not) working services here: https://github.com/audiconnect/audi_connect_ha/discussions/282

I guess my PR won't help here: https://github.com/audiconnect/audi_connect_ha/pull/281 as it really seems to be the broken API

**Comment by coreywillwhat** [comment]
Is preheater working for you? What about Lock/Unlock?

**Comment by coreywillwhat** [comment]
Closing due to stale/lack of response. Please report any services which aren't working after upgrading to the latest version of this integration.
