### ISSUE TITLE
start climatisation

### ISSUE THREAD

**Issue by Ralf-Th** [audiconnect/audi_connect_ha#264]
Hello,
I get this error for my Q4 from 2021

any idea?

Logger: custom_components.audiconnect.util
Quelle: custom_components/audiconnect/util.py:25
Integration: Audi Connect Q4 ([Dokumentation](https://github.com/acdcnow/HA_audi_connect_q4), [Probleme](https://github.com/acdcnow/HA_audi_connect_q4/issues))
Erstmals aufgetreten: 12:46:46 (1 Vorkommnisse)
Zuletzt protokolliert: 12:46:46

Unable to start climatisation of vehicle wauzzzfz0np018811: 403, message='', url=URL('https://msg.volkswagen.de/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZZZxxxxxxxxx/climater/actions')

**Comment by Heelderpeel** [comment]
same for me

**Comment by t0bias-r** [comment]
same like #262

**Comment by oleg-d** [comment]
For me start_climatisation works, myAudi app on my phone confirms the clima is indeed enabled. Car is 2020 e-tron.

But fails to refresh the data, and audiconnect.refresh_data does not update climatisation status for example.

**Comment by coreywillwhat** [comment]
Is this still an issue?

**Comment by coreywillwhat** [comment]
Closing due to lack of response. As far as I'm aware climate control has been working since recent updates and haven't heard otherwise. Please report any issues you're having.
