### ISSUE TITLE
Entity not available : location device tracker

### ISSUE THREAD

**Issue by guidokieboom** [audiconnect/audi_connect_ha#270]
The battery range (secondary engine) still doesn't work. I've installed the latest version (77e36ba). 
<img width="323" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/147da73f-f0d6-4a17-9407-cf029c4d3d9e">
My entities list shown no sensor about secondary engine range.
<img width="975" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/401c1826-584c-4a63-a6c4-01a1ef46d101">
Maybe following helps to troubleshoot:
<img width="541" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/43b7cdcd-ab0f-49a8-8ecd-841e1016d237">

**Comment by guidokieboom** [comment]
The above was 'solved' by a HA Reboot (obviously a HA restart, which I did few times before, did not work. 

However... After the HA full reboot, the location device tracker became unavailable. I've downloaded log file and removed all non-audi connect related log lines.

[home-assistant_audiconnect_2024-03-08T10-46-48.632Z.log](https://github.com/arjenvrh/audi_connect_ha/files/14537242/home-assistant_audiconnect_2024-03-08T10-46-48.632Z.log)

**Comment by Ingrimmsch93** [comment]
You get HTTP code 429, that means too many requests. You have to until tomorrow (UTC) to be able to make new requests.
So in best case deactivate the integration and try again tomorrow :)

**Comment by guidokieboom** [comment]
thank you @Ingrimmsch93 for your guidance. I did not realise I had done so many requests.. I have restarted / rebooted only couple of times today; but maybe that is already too much. I have disabled the integrations and will enable tomorrow.

**Comment by guidokieboom** [comment]
this morning I enabled the audi connect app... still device tracker entity unavailable. later this morning it became visible.
