### ISSUE TITLE
Stopped working again... no data

### ISSUE THREAD

**Issue by tomasenskede** [audiconnect/audi_connect_ha#271]
![image](https://github.com/audiconnect/audi_connect_ha/assets/32595351/b75436d4-d543-4aad-8cb7-0480328d64e2)

has Audi changed the API again?

**Comment by strutings** [comment]
still working here

**Comment by brianschrameck** [comment]
I just installed and am only getting three entities populated:

<img width="616" alt="Screenshot 2024-03-08 at 10 35 29 PM" src="https://github.com/audiconnect/audi_connect_ha/assets/1137214/d5f997ed-c436-4a19-99cb-6781bfa94f87">

**Comment by tomasenskede** [comment]
Its up working again, Audi issue I assume. Thanks for now!
