### ISSUE TITLE
a request to add additional sensors

### ISSUE THREAD

**Issue by Heelderpeel** [audiconnect/audi_connect_ha#280]
would someone like to see if it is possible to add the unique sensors from this fork. https://github.com/cyr-ius/hass-audiconnect
For example, tire information, preheat temp., charging time, etc.
In my opinion, there are some nice additions in it.

https://github.com/cyr-ius/hass-audiconnect

**Comment by superpower10** [comment]
+1 

Especially for tire pressure

**Comment by cdnninja** [comment]
Can you check if the data is in the mobile app? Some data points were recently removed from audi's API.  Also enable debug logging and post your vehicle data.

**Comment by Heelderpeel** [comment]
A lot of information is not available in the app.
The existing sensors are also not all visible in the app, so it is difficult to say.

**Comment by cdnninja** [comment]
Yes. Once debug logs are provided we can take a look.  To confirm that branch you shared no longer work for that data?

**Comment by Heelderpeel** [comment]
uhhh, I switched back to this github last week, I no longer have the Cyr-ius fork running, so I can no longer generate a debug log. (except that I don't really know how to do this either)
Is anyone else still using the Cyr-ius fork?

I can give you the yaml sensor data from the Cyr-ius fork, if that is of any use to you.

In the worst case, I have to set up a Test home assistant environment, but then I have to gather some hardware first.
I would like to hear from you what is the smartest thing to do.

**Comment by Heelderpeel** [comment]
This is the yaml

**Comment by Heelderpeel** [comment]
"""Support for Audi Connect sensors."""
from __future__ import annotations

import logging

from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass as dc,
    BinarySensorEntity,
)
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback

from .const import DOMAIN
from .entity import AudiEntity
from .helpers import AudiBinarySensorDescription

_LOGGER = logging.getLogger(__name__)


SENSOR_TYPES: tuple[AudiBinarySensorDescription, ...] = (
    AudiBinarySensorDescription(
        icon="mdi:oil",
        key="warning_oil_change",
        value_fn=lambda x: x == 1,
        translation_key="warning_oil_change",
    ),
    AudiBinarySensorDescription(
        icon="mdi:oil",
        key="oil_display",
        value_fn=lambda x: x == 1,
        entity_registry_enabled_default=False,
        translation_key="oil_display",
    ),
    AudiBinarySensorDescription(
        icon="mdi:oil",
        key="oil_level_valid",
        value_fn=lambda x: x == 1,
        entity_registry_enabled_default=False,
        translation_key="oil_level_valid",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-light-alert",
        key="light_status",
        value_fn=lambda x: x != 2,
        translation_key="light_status",
    ),
    AudiBinarySensorDescription(
        icon="mdi:lightbulb",
        key="braking_status",
        value_fn=lambda x: x != 2,
        translation_key="braking_status",
    ),
    AudiBinarySensorDescription(
        icon="mdi:power-plug",
        key="plug_state",
        device_class=dc.PLUG,
        value_fn=lambda x: True if x == "connected" else False,
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door-lock",
        key="lock_state_left_front_door",
        value_fn=lambda x: x != 2,
        device_class=dc.LOCK,
        entity_registry_enabled_default=False,
        translation_key="lock_state_left_front_door",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door-lock",
        key="lock_state_left_rear_door",
        value_fn=lambda x: x != 2,
        device_class=dc.LOCK,
        entity_registry_enabled_default=False,
        translation_key="lock_state_left_rear_door",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door-lock",
        key="lock_state_right_front_door",
        value_fn=lambda x: x != 2,
        device_class=dc.LOCK,
        entity_registry_enabled_default=False,
        translation_key="lock_state_right_front_door",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door-lock",
        key="lock_state_right_rear_door",
        value_fn=lambda x: x != 2,
        device_class=dc.LOCK,
        entity_registry_enabled_default=False,
        translation_key="lock_state_right_rear_door",
    ),
    AudiBinarySensorDescription(
        key="lock_state_trunk_lid",
        value_fn=lambda x: x != 2,
        device_class=dc.LOCK,
        entity_registry_enabled_default=False,
        translation_key="lock_state_trunk_lid",
    ),
    AudiBinarySensorDescription(
        key="lock_state_hood",
        value_fn=lambda x: x != 2,
        device_class=dc.LOCK,
        entity_registry_enabled_default=False,
        translation_key="lock_state_hood",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door",
        key="state_sun_roof_motor_cover",
        value_fn=lambda x: x != 2,
        device_class="cover",
        entity_registry_enabled_default=False,
        translation_key="state_sun_roof_motor_cover",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door",
        key="open_state_left_front_door",
        value_fn=lambda x: x != 3,
        device_class=dc.DOOR,
        entity_registry_enabled_default=False,
        translation_key="open_state_left_front_door",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door",
        key="open_state_left_rear_door",
        value_fn=lambda x: x != 3,
        device_class=dc.DOOR,
        entity_registry_enabled_default=False,
        translation_key="open_state_left_rear_door",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door",
        key="open_state_right_front_door",
        value_fn=lambda x: x != 3,
        device_class=dc.DOOR,
        entity_registry_enabled_default=False,
        translation_key="open_state_right_front_door",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-door",
        key="open_state_right_rear_door",
        value_fn=lambda x: x != 3,
        device_class=dc.DOOR,
        entity_registry_enabled_default=False,
        translation_key="open_state_right_rear_door",
    ),
    AudiBinarySensorDescription(
        key="open_state_trunk_lid",
        value_fn=lambda x: x != 3,
        device_class=dc.DOOR,
        entity_registry_enabled_default=False,
        translation_key="open_state_trunk_lid",
    ),
    AudiBinarySensorDescription(
        key="open_state_hood",
        value_fn=lambda x: x != 3,
        device_class=dc.DOOR,
        entity_registry_enabled_default=False,
        translation_key="open_state_hood",
    ),
    AudiBinarySensorDescription(
        key="state_left_front_window",
        value_fn=lambda x: x != 3,
        device_class=dc.WINDOW,
        entity_registry_enabled_default=False,
        translation_key="state_left_front_window",
    ),
    AudiBinarySensorDescription(
        key="state_left_rear_window",
        value_fn=lambda x: x != 3,
        device_class=dc.WINDOW,
        entity_registry_enabled_default=False,
        translation_key="state_left_rear_window",
    ),
    AudiBinarySensorDescription(
        key="state_right_front_window",
        value_fn=lambda x: x != 3,
        device_class=dc.WINDOW,
        entity_registry_enabled_default=False,
        translation_key="state_right_front_window",
    ),
    AudiBinarySensorDescription(
        key="state_right_rear_window",
        value_fn=lambda x: x != 3,
        device_class=dc.WINDOW,
        entity_registry_enabled_default=False,
        translation_key="state_right_rear_window",
    ),
    AudiBinarySensorDescription(
        key="state_spoiler",
        value_fn=lambda x: x != 3,
        entity_registry_enabled_default=False,
        translation_key="state_spoiler",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-tire-alert",
        key="tyre_pressure_left_front_tyre_difference",
        value_fn=lambda x: x != 1,
        device_class=dc.PROBLEM,
        entity_registry_enabled_default=False,
        translation_key="tyre_pressure_left_front_tyre_difference",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-tire-alert",
        key="tyre_pressure_left_rear_tyre_difference",
        value_fn=lambda x: x != 1,
        device_class=dc.PROBLEM,
        entity_registry_enabled_default=False,
        translation_key="tyre_pressure_left_rear_tyre_difference",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-tire-alert",
        key="tyre_pressure_right_front_tyre_difference",
        value_fn=lambda x: x != 1,
        device_class=dc.PROBLEM,
        entity_registry_enabled_default=False,
        translation_key="tyre_pressure_right_front_tyre_difference",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-tire-alert",
        key="tyre_pressure_right_rear_tyre_difference",
        value_fn=lambda x: x != 1,
        device_class=dc.PROBLEM,
        entity_registry_enabled_default=False,
        translation_key="tyre_pressure_right_rear_tyre_difference",
    ),
    AudiBinarySensorDescription(
        icon="mdi:car-tire-alert",
        key="tyre_pressure_spare_tyre_difference",
        value_fn=lambda x: x != 1,
        device_class=dc.PROBLEM,
        entity_registry_enabled_default=False,
        translation_key="tyre_pressure_spare_tyre_difference",
    ),
    AudiBinarySensorDescription(
        key="energy_flow", value_fn=lambda x: x != "off", translation_key="energy_flow"
    ),
    AudiBinarySensorDescription(
        icon="mdi:power-plug",
        key="plug_lock",
        device_class=dc.LOCK,
        value_fn=lambda x: False if x == "locked" else True,
    ),
    AudiBinarySensorDescription(
        key="preheater_active",
        value_fn=lambda x: x != "off",
        translation_key="preheater_active",
    ),
    AudiBinarySensorDescription(
        key="charging_mode",
        value_fn=lambda x: x != "off",
        translation_key="charging_mode",
    ),
    # Meta sensors
    AudiBinarySensorDescription(
        key="any_window_open",
        device_class=dc.WINDOW,
        translation_key="any_window_open",
    ),
    AudiBinarySensorDescription(
        key="any_door_open",
        device_class=dc.DOOR,
        icon="mdi:car-door",
        translation_key="any_door_open",
    ),
    AudiBinarySensorDescription(
        key="any_tyre_problem",
        icon="mdi:car-tire-alert",
        translation_key="any_tyre_problem",
    ),
)


async def async_setup_entry(
    hass: HomeAssistant, entry: ConfigEntry, async_add_entities: AddEntitiesCallback
) -> None:
    """Set up binary sensor."""
    coordinator = hass.data[DOMAIN][entry.entry_id]

    entities = []
    for vin, vehicle in coordinator.data.items():
        for name in vehicle.states:
            for description in SENSOR_TYPES:
                if description.key == name:
                    entities.append(AudiBinarySensor(coordinator, vin, description))

    async_add_entities(entities)


class AudiBinarySensor(AudiEntity, BinarySensorEntity):
    """Representation of an Audi sensor."""

    @property
    def is_on(self):
        """Return is on."""
        value = self.coordinator.data[self.vin].states.get(self.uid)
        if value and self.entity_description.value_fn:
            return self.entity_description.value_fn(value)
        return value

**Comment by Heelderpeel** [comment]
sorry iets gebeurde er op mijn PC

**Comment by cdnninja** [comment]
Debug logs from this repo are needed.

**Comment by Heelderpeel** [comment]
Okay, clearly, I just don't have much IT skills and I have no idea how to create a debug log or where to find it.
Is there a simple explanation of what you expect from me?

**Comment by Heelderpeel** [comment]
Oh, just a small comment, is that even possible, because the Cyr-ius fork is not working at all at this moment.

**Comment by cdnninja** [comment]
Yes.  Will work on docs at some point.  If you go to the integration page in HA and click the enable debug logs button.  After that the main home assistant logs will have debug logging.   May need to reload the integration to take effect.

**Comment by Heelderpeel** [comment]
Unfortunately it doesn't work, I can no longer install the integration.
![Schermafbeelding 2024-03-13 192908](https://github.com/audiconnect/audi_connect_ha/assets/23437844/720e467a-5759-4ad0-bd7c-7d1c1ba18acb)

**Comment by cdnninja** [comment]
So this integration isn't working for you?   If you want the other one please ask on that GitHub page.   Debug logs from this repo are needed.

**Comment by Heelderpeel** [comment]
Is this what we are looking for?
https://github.com/cyr-ius/hass-audiconnect/files/14417395/config_entry-audiconnect-a822b94995e84ebc08e4f7f866511bea.json

**Comment by coreywillwhat** [comment]
@cdnninja I'm not seeing tire info in the data anywhere. I dug into @cyr-ius [audiconnectpy/services.py](https://github.com/cyr-ius/audiconnectpy/blob/504d0d62c3da428910c850e0b7c21e9fb9bc1931/audiconnectpy/services.py) and looks like there are a lot more endpoints they are using for polling data maybe? Let me know what you think.

**Comment by cdnninja** [comment]
I'm not sure if they exist in the new api?

**Comment by coreywillwhat** [comment]
yeah taking more time to compare, I think you're right. I'm not seeing any others.

**Comment by coreywillwhat** [comment]
@Heelderpeel unfortunately it doesn't seem like Audi is providing all the data they used to. If the app has it, we can likely get it, and we can do our best to keep an eye on the data thats coming through the api and add them as they come.

I think we'll have to close this one for now, but please open new issues if you have them or if you see new sensors we can add.

let me know what you think.
