### ISSUE TITLE
[FR] Aggregate tyre/window/door problem sensors

### ISSUE THREAD

**Issue by wigster** [audiconnect/audi_connect_ha#283]
Currently the integration output a separate sensor for ever door, window and tyre. 

The cyrrius branch has helpful aggregate sensors be default -- one for windows, one for doors and one for tyres which I guess were just switched to on if any of the underlying binary_sensors was on. 

This is easy enough to do as a template sensor of course, but I think it would be useful to generate automatically, so that this can be put in the UI for the less technical users.

**Comment by Kolbi** [comment]
Everything except tyres should already work?

**Comment by wigster** [comment]
I think you are right -- they have different names in this branch and I missed them. I close this, since the tyres are being tracked in another issue
