### ISSUE TITLE
Remaining charge time missing

### ISSUE THREAD

**Issue by sebadv** [audiconnect/audi_connect_ha#285]
After the whole APi issue previous weeks there is 1 sensor I miss that I used.
For me: sensor.audi_q3_sportback_tfsi_e_remaining_charge_time is missing

I had some automations running on that information. Can this be added again?

TIA

**Comment by cdnninja** [comment]
Is this data in your native app? If so please enable debug logging and post your vehicle response.

**Comment by sebadv** [comment]
> Is this data in your native app? If so please enable debug logging and post your vehicle response.

If you can tell me how, no prob.
This was and still is available data. I had it in the previous integration in HA.

**Comment by cdnninja** [comment]
The Audi api changed unfortunately so not all data is. 

To enable debug go to the integration in home assistant and click enable debug logging. Reload the integration and logs should show the data now.  If more detailed steps are needed I will need to be by a pc to write them.

**Comment by Kolbi** [comment]
I used this variable also in the past - in the app it's still there,

In the past the following api delivered the information: https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/batterycharge/v1/Audi/CH/vehicles/[VIN]/charger
Output was:
`{
  "charger": {
    "settings": {
      "maxChargeCurrent": {
        "content": 32,
        "timestamp": "2024-02-07T04:51:06Z"
      },
      "chargeModeSelection": {
        "modificationState": {
          "content": "canNotBeModified",
          "timestamp": "2024-02-07T04:51:06Z"
        },
        "modificationReason": {
          "content": "systemOff",
          "timestamp": "2024-02-07T04:51:06Z"
        },
        "value": {
          "content": "timerBasedCharging",
          "timestamp": "2024-02-07T04:51:06Z"
        }
      }
    },
    "status": {
      "chargingStatusData": {
        "chargingMode": {
          "content": "off",
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "chargingStateErrorCode": {
          "content": 0,
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "chargingReason": {
          "content": "invalid",
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "externalPowerSupplyState": {
          "content": "unavailable",
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "energyFlow": {
          "content": "off",
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "chargingState": {
          "content": "off",
          "timestamp": "2024-02-07T04:51:03Z"
        }
      },
      "cruisingRangeStatusData": {
        "engineTypeFirstEngine": {
          "content": "petrolGasoline",
          "timestamp": "2024-02-07T04:51:09Z"
        },
        "primaryEngineRange": {
          "content": 440,
          "timestamp": "2024-02-07T04:51:09Z"
        },
        "hybridRange": {
          "content": 453,
          "timestamp": "2024-02-07T04:51:09Z"
        },
        "engineTypeSecondEngine": {
          "content": "typeIsElectric",
          "timestamp": "2024-02-07T04:51:09Z"
        },
        "secondaryEngineRange": {
          "content": 13,
          "timestamp": "2024-02-07T04:51:09Z"
        }
      },
      "ledStatusData": {
        "ledColor": {
          "content": "none",
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "ledState": {
          "content": "off",
          "timestamp": "2024-02-07T04:51:03Z"
        }
      },
      "batteryStatusData": {
        "stateOfCharge": {
          "content": 25,
          "timestamp": "2024-02-07T04:51:09Z"
        },
        "remainingChargingTime": {
          "content": 65535,
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "remainingChargingTimeTargetSOC": {
          "content": "maxSOC",
          "timestamp": "2024-02-07T04:51:03Z"
        }
      },
      "plugStatusData": {
        "plugState": {
          "content": "disconnected",
          "timestamp": "2024-02-07T04:51:03Z"
        },
        "lockState": {
          "content": "unlocked",
          "timestamp": "2024-02-07T04:51:03Z"
        }
      }
    }
  }
}`

Sadly https://emea.bff.cariad.digital/vehicle/v1/vehicles/[VIN]/selectivestatus doesn't provides us this information. Need to find out which API curently delivers it into the app :)

**Comment by ghostwind66** [comment]
I can also confirm that is an issue as well is happening on my instance as well.

**Comment by t0bias-r** [comment]
The remaining charging time is available only when charging is active.
The json above mentions `chargingMode: off`, so it looks ok that `remainingChargingTime` is `65535` (=16 bit value 0xFFFF).
Start a charging session and post the json again.

I guess it's because newer cars use `remainingChargingTimeToComplete_min` and your Q3 uses `remainingChargingTime`

**Comment by Kolbi** [comment]
I can now verify, I reloaded the integration while charging and remainingChargingTime came back.

So get_charger which is used by audi_connect_account retrieves this information and creates the entity.

After that update_vehicle_statusreport retrieves the information and update remainingChargingTime from https://{region}.bff.cariad.digital/vehicle/v1/vehicles/{vin}/selectivestatus?jobs={jobs}

Sum up:
* entitiy is created with audi_connect_account while charging => if not available although create entity or create with update_vehicle_statusreport
* entity is updated with update_vehicle_statusreport as long as vehicle is charging, after charging the value is not delivered and last value remains (10min in my case) => if not available set to 0

**Comment by ghostwind66** [comment]
I am still having the same issue even after charging. 

`2024-03-19 14:28:52.414 DEBUG (MainThread) [custom_components.audiconnect.audi_services] audiconnect - Car Data: {'access': {'accessStatus': {'value': {'overallStatus': 'safe', 'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 8, 7, 45, tzinfo=datetime.timezone.utc), 'doors': [{'name': 'bonnet', 'status': ['closed']}, {'name': 'frontLeft', 'status': ['locked', 'closed']}, {'name': 'frontRight', 'status': ['locked', 'closed']}, {'name': 'rearLeft', 'status': ['locked', 'closed']}, {'name': 'rearRight', 'status': ['locked', 'closed']}, {'name': 'trunk', 'status': ['locked', 'closed']}], 'windows': [{'name': 'frontLeft', 'status': ['closed']}, {'name': 'frontRight', 'status': ['closed']}, {'name': 'rearLeft', 'status': ['closed']}, {'name': 'rearRight', 'status': ['closed']}, {'name': 'roofCover', 'status': ['unsupported']}, {'name': 'sunRoof', 'status': ['unsupported']}], 'doorLockStatus': 'locked'}}}, 'charging': {'batteryStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 10, 53, 35, tzinfo=datetime.timezone.utc), 'currentSOC_pct': 100, 'cruisingRangeElectric_km': 53}}, 'chargingStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 10, 53, 35, tzinfo=datetime.timezone.utc), 'chargingState': 'readyForCharging', 'chargeMode': 'manual', 'chargeType': 'unsupported'}}, 'plugStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 10, 53, 35, tzinfo=datetime.timezone.utc), 'plugConnectionState': 'connected', 'plugLockState': 'locked', 'externalPower': 'ready', 'ledColor': 'none'}}, 'chargeMode': {'value': {'preferredChargeMode': 'manual', 'availableChargeModes': []}}}, 'chargingTimers': {'chargingTimersStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 11, 22, 28, 49, tzinfo=datetime.timezone.utc), 'timeInCar': '', 'timers': [{'id': 1, 'enabled': False, 'climatisation': False, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTimeLocal': '00:00', 'endTimeLocal': '00:00'}], 'recurringTimer': {'departureTimeLocal': '12:00', 'targetTimeLocal': '12:00', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}, {'id': 2, 'enabled': False, 'climatisation': False, 'preferredChargingTimes': [{'id': 1, 'enabled': False, 'startTimeLocal': '00:00', 'endTimeLocal': '00:00'}], 'recurringTimer': {'departureTimeLocal': '12:00', 'targetTimeLocal': '12:00', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}]}}}, 'climatisationTimers': {'climatisationTimersStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 11, 22, 28, 49, tzinfo=datetime.timezone.utc), 'timers': [{'id': 1, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2024-02-05T09:30:00', 'targetDateTimeLocal': '2024-02-05T09:30:00'}}]}}}, 'fuelStatus': {'rangeStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 10, 53, 35, tzinfo=datetime.timezone.utc), 'carType': 'hybrid', 'primaryEngine': {'type': 'gasoline', 'currentSOC_pct': 92, 'remainingRange_km': 490, 'currentFuelLevel_pct': 92}, 'secondaryEngine': {'type': 'electric', 'currentSOC_pct': 100, 'remainingRange_km': 53}, 'totalRange_km': 543}}}, 'measurements': {'rangeStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 10, 53, 35, tzinfo=datetime.timezone.utc), 'electricRange': 53, 'gasolineRange': 490, 'totalRange_km': 543}}, 'odometerStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 8, 7, 45, tzinfo=datetime.timezone.utc), 'odometer': 24988}}, 'fuelLevelStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 10, 53, 35, tzinfo=datetime.timezone.utc), 'currentFuelLevel_pct': 92, 'currentSOC_pct': 100, 'primaryEngineType': 'gasoline', 'secondaryEngineType': 'electric', 'carType': 'hybrid'}}}, 'vehicleLights': {'lightsStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 8, 7, 45, tzinfo=datetime.timezone.utc), 'lights': [{'name': 'right', 'status': 'off'}, {'name': 'left', 'status': 'off'}]}}}, 'vehicleHealthInspection': {'maintenanceStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 19, 8, 7, 41, tzinfo=datetime.timezone.utc), 'inspectionDue_days': 703, 'inspectionDue_km': 29100, 'mileage_km': 24988, 'oilServiceDue_days': 703, 'oilServiceDue_km': 29100}}}}
2024-03-19 14:28:53.853 ERROR (MainThread) [homeassistant.components.device_tracker] Platform audiconnect does not generate unique IDs. ID Audi A3 Sportback TFSI e Position already exists - ignoring device_tracker.audi_a3_sportback_tfsi_e_position
`

**Comment by Kolbi** [comment]
Can you please test with upcoming v1.0.1 again? Or with latest master?

**Comment by ghostwind66** [comment]
@Kolbi. I just installed v1.0.1 and the issue is resolved.
