### ISSUE TITLE
Audi Q8 e-tron almost no data and nothing useful

### ISSUE THREAD

**Issue by ngluvakov** [audiconnect/audi_connect_ha#291]
I used to own an ICE Q8 just two weeks ago, and I was thrilled to use your fantastic integration. I had numerous sensors on it. When I switched my car, all I get now is this:

- audi q8 sportback e tron longterm trip data
- audi q8 sportback e tron longterm trip user reset
- audi q8 sportback e tron shortterm trip data
- audi q8 sportback e tron shortterm trip user reset
- Audi Q8 Sportback e-tron Climatisation state - with 

wrong data
- Audi Q8 Sportback e-tron Model

All of them have the status "unknown", and The only control I have is for the door-door lock, with no control over the car. 

Please let me know if there is something I can do to help you with this. I saw in the previous subject that you're asking for the API data, so if you tell me how to do that, I will gladly provide it. 

Many thanks for this integration.
![Screenshot_5](https://github.com/audiconnect/audi_connect_ha/assets/129649324/4910e5e2-07ee-4a70-b8e0-40f00e3610be)
![Screenshot_4](https://github.com/audiconnect/audi_connect_ha/assets/129649324/cfef58e9-4215-4265-a2d1-4c6cc7f6902a)

**Comment by cdnninja** [comment]
Out of interest did it start working?

**Comment by ngluvakov** [comment]
Unfortunately, no. I only got new problems. I believe I used it too often, and my car is now not allowed on the server. I have no other explanation. I got all the info down to the smallest detail in one moment. I was happy, and I closed the subject. I got the idea to follow the charging more closely, so I put the update period to 1 minute. I suspect that made the car send too many requests, and it ended up badly. 
![Screenshot_20240315_134720_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/d796388f-1e8e-40a4-a5b7-69150df58632)
![Screenshot_20240315_134915_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/e524f977-c089-4920-a430-cb232b09cf03)
![Screenshot_20240315_134928_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/36728de1-3d2d-4dad-ac2c-9e8e765ddb95)
![Screenshot_20240315_134940_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/b438c25c-20be-4360-ab3d-cc6e2d5a4739)
![Screenshot_20240315_134944_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/676d1e9d-f9ba-4162-9cae-d0a9f453633f)
![Screenshot_20240319_160344_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/7e2be5e4-91e4-460c-98ef-39f677e7c1da)
![Screenshot_20240319_094156_myAudi](https://github.com/audiconnect/audi_connect_ha/assets/129649324/f38a63fb-0c49-4313-8e99-d74a5b61acc8)

**Comment by ngluvakov** [comment]
In the meantime, Porsche Serbia called me and suggested I delete the old account and create a new one. I did that, but I got no results. Every option and information is lost now. Connect doesn't work for me.

**Comment by alxwolf** [comment]
> Connect doesn't work for me.

@ngluvakov Ah, don't worry and try again in some days. Audi backend servers are one big mess sometimes.

And if that's not the case, there is a limit (IIRC about 50) of inquiries allowed to be sent to the car before it stops responding. Basically to protect the starter battery from draining too much.

**Comment by coreywillwhat** [comment]
@ngluvakov Has your access been restored, using any of the most recent versions?

**Comment by coreywillwhat** [comment]
Closing due to lack of response. #372 resolved Q4 owners, I would expect this did the same for e-tron. trip data is planned under #382

**Comment by ngluvakov** [comment]
Hello. I'm sorry for not getting back to you sooner. My work prevented me from answering earlier. It is all resolved now. I am updating my car data at 15-minute intervals. It is working fine. Thank you for creating such a fantastic piece of integration. 

Regards from Serbia,
Nik
