### ISSUE TITLE
Last update is a string instead of a datetime.

### ISSUE THREAD

**Issue by wigster** [audiconnect/audi_connect_ha#299]
The sensor.<name>_last_update state is interpreted as a string instead of a datetime. 

Possibly, it is just missing the 'device_class: timestamp' attribute. 

As it is, the sensor does not get reformatted to e.g. relative time by the UI.

**Comment by Kolbi** [comment]
Can you check https://github.com/audiconnect/audi_connect_ha/pull/300 ?

**Comment by wigster** [comment]
It doesn't seem to solve the problem. In the entities card:

![image](https://github.com/audiconnect/audi_connect_ha/assets/10956987/0a3b850c-190d-4684-a406-1a913d363174)

I still do not have the device_class in the attributes of the entity. I have checked that the dashboard.py contains your latest changes from #300

**Comment by wigster** [comment]
Yep can confirm it works in your branch

**Comment by Kolbi** [comment]
I close this case, as I guess the https://github.com/audiconnect/audi_connect_ha/pull/300 will be merged today or tomorrow @cdnninja
