### ISSUE TITLE
Missing entity sun_roof

### ISSUE THREAD

**Issue by over40** [audiconnect/audi_connect_ha#301]
Dear Team, i am missing one entity for my Audi Q3, which i think to have seen it in a previous version.
![sunroof](https://github.com/audiconnect/audi_connect_ha/assets/7571285/c2f2d32f-f5c4-47d4-afb2-c297532aefb7)

File: /homeassistant/custom_components/audiconnect/dashboard.py - BinarySensor(attr="sun_roof", name="Sun roof", device_class="window")
But i am not sure 100%.

**Comment by coreywillwhat** [comment]
Can you turn on debugging, wait for a refresh interval and provide the file?

**Comment by over40** [comment]
After i have updated newest version (v1.0.2) from today sunroof-state is available again. Thank you for response.
![audiconnect_v1 0 2](https://github.com/audiconnect/audi_connect_ha/assets/7571285/5c925d85-ad48-49d0-9f99-39345cdfb97d)
![sunroof](https://github.com/audiconnect/audi_connect_ha/assets/7571285/06902c95-e04c-44c5-9e07-d58e95f5e311)

**Comment by over40** [comment]
solved with the newest version v 1.0.2
