### ISSUE TITLE
Last Trip data 

### ISSUE THREAD

**Issue by Svarstad** [audiconnect/audi_connect_ha#308]
I miss the ability to see the last trip information in the integration. 
I scrolled quickly to see if it was implemented but could not see any, is this possible to get out of the API? 
Edit: I found "vehicle.async_get_tripdata"
Is it limited due lack of subscriptions from Audi? 

My previous car was a Volkswagen and I used this integration to get this type of data: 
https://github.com/robinostlund/homeassistant-volkswagencarnet

I had to have an active subscription to collect any type of data in that integration so not sure how this works.

![Skjermbilde 2024-03-25 kl  11 50 06](https://github.com/audiconnect/audi_connect_ha/assets/24622052/9bc4fcf8-34b9-4833-83f9-7057efb6bb54)

**Comment by coreywillwhat** [comment]
Thanks for your interest in this information!
Unfortunately, This is known to not be working at the moment. With API change, the structure is different and needs to be adapted. Closing to capture all related under a catch all issue: #344
