### ISSUE TITLE
HACS does not report an update is available for new releases

### ISSUE THREAD

**Issue by oleg-d** [audiconnect/audi_connect_ha#313]
HACS doesn't seem to report when a new update is available automatically. 

Today v1.0.2 was released but HACS is not reporting it. I observed the same thing when I had 1.0.0 installed and 1.0.1 was released but wanted to see it reproducing to be sure.

If I open the integration in HACS click the 3 dots and click Redownload then the newest version is refreshed.

**Comment by coreywillwhat** [comment]
Seems like this is expected behavior: https://hacs.xyz/docs/basic/updates/
At startup or every 48 to 96 hours after that.

**Comment by oleg-d** [comment]
Ah I see, thanks for pointing that out
