### ISSUE TITLE
sensor oil_level

### ISSUE THREAD

**Issue by Theandone90** [audiconnect/audi_connect_ha#314]
Hello,

From the new version, the oil_level sensor no longer goes up.
This sensor gives me the oil_level as a pourcentage.
Do you have an idea ?

**Comment by Kolbi** [comment]
Maybe related to: https://github.com/audiconnect/audi_connect_ha/issues/297 

Which vehicle you onw? Any logs what you get from API?

**Comment by Theandone90** [comment]
My car is A3 Sportback S-Line 2021.
[audi-log.log](https://github.com/audiconnect/audi_connect_ha/files/14874171/audi-log.log)

**Comment by coreywillwhat** [comment]
> My car is A3 Sportback S-Line 2021. [audi-log.log](https://github.com/audiconnect/audi_connect_ha/files/14874171/audi-log.log)

I'm not seeing this value being provided by the API anymore:
`textId:OIL_LEVEL_DIPSTICKS_PERCENTAGE loc:['oilLevel', 'oilLevelStatus', 'value', 'value']: val:None ts:None`

@neil-bh can you provide a log? integrations > audiconnect > enable debug logging. Run the `refresh_cloud_data` service. Then disable debug logging and provide the file?

I'm guessing this isn't provided by the API anymore. My car is also reporting `None` value.

**Comment by neil-bh** [comment]
No problem, see attached -->
[home-assistant_audiconnect_2024-04-08T19-50-31.509Z.log](https://github.com/audiconnect/audi_connect_ha/files/14910384/home-assistant_audiconnect_2024-04-08T19-50-31.509Z.log)

 I seem to be getting this returned:
`textId:OIL_LEVEL_DIPSTICKS_PERCENTAGE loc:['oilLevel', 'oilLevelStatus', 'value', 'carCapturedTimestamp']: val:True ts:2024-04-06 09:40:10+00:00`

That's odd, why would it be returning a timestamp?

I can also see some data the ends with something like:
`.........., 'inspectionDue_days': 82, 'inspectionDue_km': 20278, 'mileage_km': 16779, 'oilServiceDue_days': 82, 'oilServiceDue_km': 12875}}}}`

...this doesn't seem to contain any oil level values either (apart from service due), but i'm lost in these logs, so I won't pretend I know what I'm talking about.

What are your thoughts?

**Comment by coreywillwhat** [comment]
The returned value is actually "True" if you see `val:True`.
`ts:` is for timestamp.

It seems with API changes they've either moved away from using this, or its actually just a bool value for if the oil level is good (`True`) or bad (`False`). If its changed to that, we'll have to modify the sensor to binary_sensor and return the correct device_class to make this worthwhile. Its definitely not providing percentage anymore from what i've seen.

I'm just not sure why you would be returning `True` while mine is returning `None`. Could be a difference between diesel providing the value vs gas/electric not providing the value.

**Comment by neil-bh** [comment]
Sounds like you could be right.  The Audi app on my phone is reporting `OK`.  I'm not sure if in the past this was an integer value - can't say I paid much attention.
![Screenshot_20240408-211712](https://github.com/audiconnect/audi_connect_ha/assets/517465/f7b43b62-411f-4b19-9359-df8f7474edb5)

Also, in the service schedule section of the phone app, it provides a date for the oil change.  I'm not sure how that's calculated if it doesn't know the level of oil.  Maybe it's an estimation based on the last time the car had an oil change?  If thats so, that'd be a semi-useful value to report on perhaps.
![Screenshot_20240408-211822](https://github.com/audiconnect/audi_connect_ha/assets/517465/9f7d3fce-e093-4afb-86b8-9e162362c73f)

**Comment by coreywillwhat** [comment]
This is great info. Thanks for providing this. I can put together a PR for a binary sensor for the "oil level" since that seems to be its purpose now.

As for the service schedule, these sensors should be available already. Do you have these sensors available for your car?
![image](https://github.com/audiconnect/audi_connect_ha/assets/104224685/667a731f-5877-403b-baae-24e7b21119e1)
![image](https://github.com/audiconnect/audi_connect_ha/assets/104224685/92ff7461-c624-4bdf-a3e4-b3ed71dbf30f)

**Comment by neil-bh** [comment]
Glad I could provide some help to the future changes.
I'll just have to kiss my Oil Level Gauge Card goodbye.

As for the service schedule, yes, I double checked and I can see these entities already.

**Comment by coreywillwhat** [comment]
> I'll just have to kiss my Oil Level Gauge Card goodbye.
Sorry for your loss 😞 
Okay so for this its just the oil level. Service schedule and oil change are working for you.

**Comment by Kolbi** [comment]
`2024-04-09 07:34:12.354 DEBUG (MainThread) [custom_components.audiconnect.audi_models] audi_models.py - _tryAppendFieldWithTs: textId:OIL_LEVEL_DIPSTICKS_PERCENTAGE loc:['oilLevel', 'oilLevelStatus', 'value', 'carCapturedTimestamp']: val:True ts:2024-04-08 15:27:43+00:00`

The Web API still delivers it as an percentage: https://userinfo.my.audi.com/bvh/v1

```
data.vehicleStatusReport.oilLevel {
  "value": 87,
  "unit": "%"
}
```

Maybe we need to think if the should integrate this API as well.

Full data:
`{
    "data": {
        "vehicleStatusReport": {
            "vin": "WAUZZZF23[XXX]",
            "vehicleType": "HYBRID",
            "lastUpdated": "2024-04-09T03:55:14Z",
            "engines": [
                {
                    "type": "GASOLINE",
                    "range": {
                        "value": 670,
                        "unit": "km"
                    },
                    "filling": {
                        "value": 93,
                        "unit": "%"
                    },
                    "adBlueRange": null,
                    "electric": null
                },
                {
                    "type": "ELECTRIC",
                    "range": {
                        "value": 15,
                        "unit": "km"
                    },
                    "filling": {
                        "value": 22,
                        "unit": "%"
                    },
                    "adBlueRange": null,
                    "electric": {
                        "chargingState": "INACTIVE",
                        "chargingTime": null
                    }
                }
            ],
            "totalRange": {
                "value": 685,
                "unit": "km"
            },
            "mileage": {
                "value": 20483,
                "unit": "km"
            },
            "oilLevel": {
                "value": 87,
                "unit": "%"
            },
            "oilLevelSupported": true,
            "service": {
                "oilChange": {
                    "time": {
                        "value": -193,
                        "unit": "d"
                    },
                    "distance": {
                        "value": -9600,
                        "unit": "km"
                    }
                },
                "inspection": {
                    "time": {
                        "value": -193,
                        "unit": "d"
                    },
                    "distance": {
                        "value": -9600,
                        "unit": "km"
                    }
                }
            },
            "messages": [
                {
                    "key": "vehicle.locked",
                    "value": true
                },
                {
                    "key": "doors.closed",
                    "value": true
                },
                {
                    "key": "windows.closed",
                    "value": true
                },
                {
                    "key": "parking.lights.off",
                    "value": true
                },
                {
                    "key": "bonnet.closed",
                    "value": true
                },
                {
                    "key": "trunk.closed",
                    "value": true
                }
            ],
            "stoWarnings": []
        }
    }
}`

**Comment by coreywillwhat** [comment]
Oh nice catch @Kolbi .
Yeah maybe thats something we could do to get the Oil Level back as a separate sensor to the binary? Is that what you're thinking?

**Comment by Theandone90** [comment]
I have a same result before reload cloud data Audi.
textId:OIL_LEVEL_DIPSTICKS_PERCENTAGE loc:['oilLevel', 'oilLevelStatus', 'value', 'value']: val:None ts:None

**Comment by Kolbi** [comment]
Just link it here: https://github.com/audiconnect/audi_connect_ha/discussions/276
