### ISSUE TITLE
Error in log after Start Climate Control

### ISSUE THREAD

**Issue by Heelderpeel** [audiconnect/audi_connect_ha#324]
First let me say that I'm thrilled about the addition of this feature.
And it works fine for me, I only see that there are some errors in the log and that therefore the climatisation_state sensor does not change status. again I don't mind, it's more For Your Information.
These are the loggings:

Logger: custom_components.audiconnect.util
Bron: custom_components/audiconnect/util.py:25
integratie: Audi Connect (documentation, issues)
First occurred: 14:26:42 (1 gebeurtenissen)
Laatst gelogd: 14:26:42

Unable to refresh vehicle data of wauzzzfy5l2121367: 403, message='', url=URL('https://msg.volkswagen.de/fs-car/bs/vsr/v1/Audi/DE/vehicles/WAUZZZFY********/requests')

Logger: custom_components.audiconnect.audi_account
Bron: /config/custom_components/audiconnect/audi_account.py:266
integratie: Audi Connect (documentation, issues)
First occurred: 14:26:42 (1 gebeurtenissen)
Laatst gelogd: 14:26:42

Error refreshing vehicle data wauzzzfy**********
NoneType: None

**Comment by coreywillwhat** [comment]
This is expected until `refresh_vehicle_data` is fixed, as that is requested immediately upon completion of the `start_climate_control` action.

In my testing, the vehicle action is still executed and climate control is started.

Keep an eye out for more updates on here, I will be submitting some updates which will help with the sensors updating much quicker.

**Comment by Heelderpeel** [comment]
okay sorry, then maybe you could close this one.

**Comment by coreywillwhat** [comment]
Others will have the same issue/question, so we may as well keep this open until we have an actual fix in the pipeline.

**Comment by Heelderpeel** [comment]
I would love to help on this project, but I have 0 programming skills, so I'm afraid I can only do some testing.
or just walk to the coffee machine to get a cup of coffee for everyone. :-)

**Comment by coreywillwhat** [comment]
#325 PR open for `refresh_cloud_data` service call. This can be called after a vehicle service request to update data from the cloud. In testing ~30 seconds between the vehicle service call and the `refresh_cloud_data` will have the updated information so long as the car has checked-in after execution.

Note this will not solve the `refresh_vehicle_data` error seen in the logs.

**Comment by coreywillwhat** [comment]
#327 if refresh_vehicle_data fails, adds a cloud data update after a delay,
FYI I'm tagging this issue to the PRs, not necessarily adding for your awareness haha

**Comment by coreywillwhat** [comment]
as discussed, the underlying issue for this is #330 . Closing this issue as part of cleanup. Let me know if you have any concerns.
