### ISSUE TITLE
Make mileage sensor total_increasing

### ISSUE THREAD

**Issue by wigster** [audiconnect/audi_connect_ha#333]
version: 1.1.0

The mileage sensor seems to be missing some attributes which would allow it to be included in long term statistics and then plotted using the statistics graph card. 

I believe it should have a state_class of total_increasing but maybe it’s also a question device_class?

**Comment by Kolbi** [comment]
Hi @wigster makes totally sense for me, I already implemented it in https://github.com/audiconnect/audi_connect_ha/pull/334

Do you know other entities which would make sense for adding a state_class ?

**Comment by wigster** [comment]
Im not sure it makes sense for the other entities I have — the range and tank level/battery level entities could be measurement state_classes, so that one could in principle use some SQL on the LTS data to process it, but I am not sure it would be that useful. 

I’ve made a bunch of template sensors working off those to work out gas mileage etc which is useful to store to look for any long term trends but that’s not really possible to calculate from historical tank levels.
