### ISSUE TITLE
extension of audiconnect.start_climate_control for steering wheel heating

### ISSUE THREAD

**Issue by helmut-hackl** [audiconnect/audi_connect_ha#347]
First of all many thanks for extending this service!

I wonder, if it will be possible to extend the service call with a paramter to turn on the steering wheel heating.

**Comment by coreywillwhat** [comment]
I'll have to double check, I'm pretty sure it turns on with either the driver seat heater, or the glass surface heating.
Do you have a separate option in your Audi app for steering wheel heat?

**Comment by helmut-hackl** [comment]
No, in my audi app I have only the otion for "glass surface" heating and "comfort-climatisation".
If I turn on driver seat and glass heating, the steering wheel stays cold.
If I tunr on through the app with "comfort-climatisation" it is heating.
I don't know if there is an extra bit to set. Do you know any way to get the request on the mobile, the myaudi app is sending to the audi server?

**Comment by coreywillwhat** [comment]
I'm unsure about intercepting the API calls. There are some proxy options out there it sounds like, but I've never gotten into it. Others on here have been grabbing the calls and posting.

Let me know about the testing. I usually run my climate control ~20-25 minutes before I'm leaving. Have some automations set up to do this for me based on calendar events.

**Comment by helmut-hackl** [comment]
Yes I'll give you a update tomorrow. 

BTW, I have some automations too, and ran into troubles calling the service with node-red

My automation in hhomeassistant looks like this:

service: audiconnect.start_climate_control
data:
  vin: MY_WAUZZ
  temp_c: 22
  glass_heating: true
  seat_fl: true

and this works like a charm. Unfortunately the same call in node red does nothing:

![image](https://github.com/audiconnect/audi_connect_ha/assets/12947357/28a3b28b-ceda-45ed-8ea7-12128ebecb5c)

**Comment by helmut-hackl** [comment]
Tested this, and yes, after about 15 minutes, the steering wheel gets warm. I'm not sure if it is heated with the "glass surface heating" or the "driver seat heating" but yes, it is heating ;-)
So I'm closing this issue, thank you for your support!
