### ISSUE TITLE
Charging complete time keeps updating after charge is complete

### ISSUE THREAD

**Issue by wigster** [audiconnect/audi_connect_ha#351]
Thanks for implementing the charge complete datetime sensor. #318 

There is one behaviour that doesn't seem optimal -- the sensor keeps updating to the last_update time from the vehicle even after the charging is done. 

I would suggest a small modification: that the charging_complete_time sensor be updated as long as the _charging_state sensor has the state `charging`. Once it goes to `readyForCharging` or even `notReadyForCharging`, the _charging_complete_time sensor should stop updating, keeping its last value. 

I think this would be accurate enough, given that the car talks to the cloud often while charging and would keep the approximate last date of last charge in the sensor until the next charge.

**Comment by coreywillwhat** [comment]
FYI - This is all set, and working on my end. PR #376 submitted just needs review/merge.
