### ISSUE TITLE
Missing entity roof_cover

### ISSUE THREAD

**Issue by Kolbi** [audiconnect/audi_connect_ha#359]
JSON:
`{'access': {'accessStatus': {'value': {'overallStatus': 'unsafe', 'carCapturedTimestamp': , 'doors': [{'name': 'bonnet', 'status': ['closed']}, {'name': 'frontLeft', 'status': ['locked', 'closed']}, {'name': 'frontRight', 'status': ['locked', 'closed']}, {'name': 'rearLeft', 'status': ['locked', 'closed']}, {'name': 'rearRight', 'status': ['locked', 'closed']}, {'name': 'trunk', 'status': ['locked', 'closed']}], 'windows': [{'name': 'frontLeft', 'status': ['closed']}, {'name': 'frontRight', 'status': ['closed']}, {'name': 'rearLeft', 'status': ['closed']}, {'name': 'rearRight', 'status': ['closed']}, {'name': 'roofCover', 'status': ['unsupported']}, {'name': 'sunRoof', 'status': ['open']}], 'doorLockStatus': 'locked'}}}, 'fuelStatus': {'rangeStatus': {'value': {'carCapturedTimestamp': , 'carType': 'gasoline', 'primaryEngine': {'type': 'gasoline', 'currentSOC_pct': 43, 'remainingRange_km': 320, 'currentFuelLevel_pct': 43}, 'totalRange_km': 320}}}, 'measurements': {'rangeStatus': {'value': {'carCapturedTimestamp': , 'gasolineRange': 320, 'totalRange_km': 320}}, 'odometerStatus': {'value': {'carCapturedTimestamp': , 'odometer': 28645}}, 'fuelLevelStatus': {'value': {'carCapturedTimestamp':, 'currentFuelLevel_pct': 43, 'primaryEngineType': 'gasoline', 'carType': 'gasoline'}}}, 'vehicleLights': {'lightsStatus': {'value': {'carCapturedTimestamp': , 'lights': [{'name': 'right', 'status': 'off'}, {'name': 'left', 'status': 'off'}]}}}, 'vehicleHealthInspection': {'maintenanceStatus': {'value': {'carCapturedTimestamp': , 'inspectionDue_days': 334, 'inspectionDue_km': 24500, 'mileage_km': 28645, 'oilServiceDue_days': 249, 'oilServiceDue_km': 21700}}}}
`

**Comment by over40** [comment]
Sun roof entity is again available: binary_sensor.audi_q3_xxxxx_sun_roof
![Screenshot 2024-04-11 200359](https://github.com/audiconnect/audi_connect_ha/assets/7571285/74584417-d614-4fa1-92a0-95be2ac78cb6)
Thank you for support!

**Comment by coreywillwhat** [comment]
@Kolbi are you thinking this is related to a convertible?

**Comment by over40** [comment]
for me it is a sunroof like shown in the picture
![sunroof](https://github.com/audiconnect/audi_connect_ha/assets/7571285/f888dec5-3b21-49cd-807c-1a904b11c818)

**Comment by Kolbi** [comment]
@over40 sunroof yes you are right, but roof_cover it is for example an Audi A5 Cabriolet ?
@coreywillwhat yes I mean a convertible - it should have the roof_cover I would add this like sun_roof to the overall status for all windows

**Comment by over40** [comment]
You should make differences between it. Sunroofs you can have for several Audi models and Cabriolets are specific Audi Model types.

**Comment by Kolbi** [comment]
@over40 sure, with sun_roof our current solution is that the "open window check" only checks for an open sun_roof if there is a sun_roof available at all. For roof_cover we need the same logic only check for open roof_cover if the car has one.

We need a flexible / generic solution which fits for all models.

**Comment by coreywillwhat** [comment]
@Kolbi @cdnninja FYI I'm trying to start documenting the [JSON responses in the wiki](https://github.com/audiconnect/audi_connect_ha/wiki/JSON-Data-Structures).
