### ISSUE TITLE
Question: What is the upper limit for AdBlue (e.g. a full AdBlue tank)? 

### ISSUE THREAD

**Issue by neil-bh** [audiconnect/audi_connect_ha#399]
I'd like to create a gauge panel on my dashboard (as I have done previously to report on diesel, which shows how much is in my tank).  I have a value from AdBlue currently showing `4000` and it has a unit of measurement `km`.

Does anyone know what values I need to make a needle gauge report when my AdBlue is too low and should be topped up?  I'm guessing I need to know what value in km will represent FULL in order to get the upper and lower limits to be a useful gauge.

I'm welcome to suggestions.

And apologies for raising this as an 'issue'.  I wasn't sure how else to ask the community and devs this question otherwise.

Thanks.

**Comment by wigster** [comment]
I presume this is different for every model of the car. You could try filling the tank yourself and seeing what the app gives as the distance.

**Comment by neil-bh** [comment]
A good search has informed me that the capacity of an Audi A6 Saloon Adblue tank is 17 Litres and should be sufficient for 9,000 miles according to the car manufacturer.  That converts to 14,484.1 km.  Apparently an on screen warning shows up on the dash when the value reaches ~1500 miles (2414.016 km) to go.

So, I've put together a gauge with the following values:
<img width="287" alt="image" src="https://github.com/audiconnect/audi_connect_ha/assets/517465/c7cdb685-9bbf-448a-85cc-0f76fc29b4db">

I guess I'll find out how accurate it is some time soon. :D

Here is my gauge for reference if it interests anyone:
<img width="227" alt="image" src="https://github.com/audiconnect/audi_connect_ha/assets/517465/231cad1e-6bdf-454e-9d19-99bc463b3eb4">

**Comment by coreywillwhat** [comment]
Hi @neil-bh, no worries at all! The appropriate place for this would be under the [Discussions](https://github.com/audiconnect/audi_connect_ha/discussions) section. Marking this as invalid and closing for now, but please report back your findings if you think the reported values should be converted in any way so the user can more easily understand the reported numbers from the front end.
