### ISSUE TITLE
Sensor `charging_complete_time` unknown on A5

### ISSUE THREAD

**Issue by mm98** [audiconnect/audi_connect_ha#401]
**Describe the bug**

First of all. This isn't really a problem at all. I just wanted to report it, since it doesn't really make any sense to me 

I have a `sensor.audi_a5_sportback_charging_complete_time` sensor, which doesn't really have anything to do with my car (gasoline, A5). I can see in the code and debug logs, that the state is checked / validated by `remainingChargingTime` [here](https://github.com/audiconnect/audi_connect_ha/blob/master/custom_components/audiconnect/audi_connect_account.py#L1642-L1670):

```
TRY APPEND STATE: Searching for 'remainingChargingTime' at location=['charging', 'chargingStatus', 'value', 'remainingChargingTimeToComplete_min'], tsoff=-1
TRY APPEND STATE: 'remainingChargingTime' adjusted to 0 due to None value
TRY APPEND STATE: Timestamp for 'remainingChargingTime' is None or missing; not appending state.
```

Wouldn't this mean that it is `None` and returned as `is not supported`? Meaning the sensor would be disabled / hidden?

**Screenshots**
![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/191fdcd7-9af2-4dbc-b4c5-05650cb8df1b)

**Logfile**
[home-assistant_audiconnect_2024-04-18T13-32-10.734Z.log](https://github.com/audiconnect/audi_connect_ha/files/15025688/home-assistant_audiconnect_2024-04-18T13-32-10.734Z.log)

**Your Vehicle Details**
Model: A5 Sportback
Year: 2021
Type (ICE/PHEV/BEV): ICE

**Note:** It might be good to describe what `ICE/PHEV/BEV` is (ex. [this](https://electriccarhome.co.uk/electric-cars/bev-phev-hev-ice/)) for none native English speaking. I had to look it up ;)

**Comment by Kolbi** [comment]
Thanks for reporting. Which version are you using currently?

Good note as I even don't know the term ICE (only in combination with trains :))

**Comment by Kolbi** [comment]
Need to dig deeper but maybe this could be the issue:

`        # Special handling for remainingChargingTime
        if name == "remainingChargingTime" and val is None:
            val = 0
            _LOGGER.debug(
                "TRY APPEND STATE: 'remainingChargingTime' adjusted to 0 due to None value"
            )`

Do you also have the entity remainingChargingTime ?

In this line https://github.com/audiconnect/audi_connect_ha/blob/5055bc34b14e99fda066ce9975da9e8c98ee99da/custom_components/audiconnect/audi_connect_account.py#L1655
`        if self.last_update_time is None or self.remaining_charging_time is None:
            return None`
remaining_charging_time is 0 so not None that might be the reason why we have unknown.... :)

**Comment by mm98** [comment]
> Thanks for reporting. Which version are you using currently?

I'm using the most recent release `v1.6.3`

**Comment by mm98** [comment]
> Do you also have the entity remainingChargingTime ?

No, i don't have an entity named `remainingChargingTime`.

![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/2991e261-dc58-4123-88e6-af8f72dfd2ea)

**Comment by Kolbi** [comment]
Can you check the fix in https://github.com/audiconnect/audi_connect_ha/pull/402 ?

**Comment by Kolbi** [comment]
Maybe the fix is not working well in all cases need to think about it.

**Comment by mm98** [comment]
> Maybe the fix is not working well in all cases need to think about it.

I'll try to make the change locally and report back.

**Comment by mm98** [comment]
@Kolbi i made the change in [audi_connect_account.py](https://github.com/audiconnect/audi_connect_ha/blob/5055bc34b14e99fda066ce9975da9e8c98ee99da/custom_components/audiconnect/audi_connect_account.py#L1655) locally. Nothing changed though.

![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/3a78ec78-b33a-4d14-bb08-0308bbce4cfa)

**Comment by mm98** [comment]
Honestly, you don't need to spend much time on it for me. I just reported it in case there was an "easy" fix. It doesn't bother me at all that it's visible and I can just disable it manually.

**Comment by coreywillwhat** [comment]
I think @kolbi and I have worked this out. I will work on updating #402 when I have some time. As always, thanks for reporting @mm98 !
