### ISSUE TITLE
"State of Charge" is returning float

### ISSUE THREAD

**Issue by coreywillwhat** [audiconnect/audi_connect_ha#410]
**Describe the bug**
The sensor in HA for "State of Charge" is always returning a `float`.
Example: 60.0%

**Expected behavior**
Looking at the data from the API, an `int` is always returned for "State of Charge". There is no reason to convert to float.
Expected value: 60%

**Screenshots**
![image](https://github.com/audiconnect/audi_connect_ha/assets/104224685/9c021b75-9d78-44d1-aae2-38e38b1f2983)

**Your Vehicle Details**
Model: Q5
Year: 2021
Type (ICE/PHEV/BEV): Hybrid

**Comment by Kolbi** [comment]
Then maybe we should also change https://github.com/audiconnect/audi_connect_ha/pull/405/ as we do the same.
