### ISSUE TITLE
FR: Include light(s) status by `vehicleLights` node.

### ISSUE THREAD

**Issue by mm98** [audiconnect/audi_connect_ha#421]
**Is your feature request related to a problem? Please describe.**
My car returns the light status for `left` and `right`. This information also exist in the JSON (from debug logs)

```json
"vehicleLights": {
	"lightsStatus": {
		"value": {
			"carCapturedTimestamp": "datetime.datetime",
			"lights": [
				{
					"name": "right",
					"status": "off"
				},
				{
					"name": "left",
					"status": "off"
				}
			]
		}
	}
}
```

**Describe the solution you'd like**
Would it be possible to include these two values as sensors in this integration?

**Describe alternatives you've considered**
No alternatives.

**Additional context**
This information is also visible in the `MyAudi` app. As shown below:
![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/c9337911-62be-4cfc-8775-8ce8f3099b21)

**Logfile**
[home-assistant_audiconnect_2024-04-29T07-19-42.831Z.log](https://github.com/audiconnect/audi_connect_ha/files/15175646/home-assistant_audiconnect_2024-04-29T07-19-42.831Z.log)

**Your Vehicle Details**
Model: A5 Sportback advanced 40 TFSI S tronic
Year: 2021
Type (ICE/PHEV/BEV): ICE

**Comment by coreywillwhat** [comment]
thanks @mm98 . Great suggestion!
I'm guessing these are in reference to the interior lights? Have you tested by chance? If not I can give it a go.

**Comment by mm98** [comment]
> thanks @mm98 . Great suggestion! I'm guessing these are in reference to the interior lights? Have you tested by chance? If not I can give it a go.

Your guess is as good as mine 😄 `left` and `right` doesn't really make any sense in regard to external light (front or back).  I haven't tested myself yet, since I just noticed these in the `myAudi` app. All the checkmarks in the screenshot above is all for external "things", so i would guess - it is front left and right?

**Comment by mm98** [comment]
I just tested by turning on the ignition. Turned light off and use fog light. Nothing changed with the light status in the myAudi app.

![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/f2bddfcc-1ea2-4b23-9af1-b32e5e173f09)

**Comment by cdnninja** [comment]
Could left right lights be euro park lights? Where you park the car with your blinker enabled on one side.  It then keeps that side on for the duration of parking.  

This is typically disabled in NA. 

A guess though.

**Comment by mm98** [comment]
> Could left right lights be euro park lights?

I'll do some testing with park lights and get back to you with more info!

**Comment by mm98** [comment]
I can confirm it is parking lights. 

![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/93989b4f-94a8-46d3-b44b-397828bc67d5)

![image](https://github.com/audiconnect/audi_connect_ha/assets/992714/4f47e6b3-b71e-4e2a-8cf1-b2aab5138c55)

**Comment by coreywillwhat** [comment]
Thanks for testing @mm98 !
I'm thinking the best method for this would be a single binary sensor for All Lights with attributes for each light. Let me know what you think.

**Comment by mm98** [comment]
> Let me know what you think.

I agree. No reason to have them separate.

**Comment by coreywillwhat** [comment]
Bump
