### ISSUE TITLE
Car Position Not Updated

### ISSUE THREAD

**Issue by veiter555** [audiconnect/audi_connect_ha#428]
Car Position is not getting updated even the car is at home for several hours... After reloading the Service in Home assistant the car position will change to home. So the issue should be in the service by updating the car position dynamically

**Comment by rhoddan** [comment]
Same here

**Comment by bartlde** [comment]
My Position is fluctuating between the old position (my yesterdays trip) and the current position at home. The problem occurs since the last update. I have arrived at home yesterday evening. My original Audi APP displays the position correctly at home - with no fluctuation.

Here a copy from detailed entity view (my GUI is set to German):
wurde zuhause erkannt
11:36:12 - Vor 4 Minuten
wurde als abwesend erkannt
11:29:54 - Vor 11 Minuten
wurde zuhause erkannt
11:21:06 - Vor 19 Minuten
wurde als abwesend erkannt
11:14:45 - Vor 26 Minuten
wurde zuhause erkannt
11:06:03 - Vor 34 Minuten
wurde als abwesend erkannt
10:59:49 - Vor 41 Minuten
wurde zuhause erkannt
10:51:19 - Vor 1 Stunde
wurde als abwesend erkannt
10:44:47 - Vor 1 Stunde
wurde zuhause erkannt
10:36:05 - Vor 1 Stunde
wurde als abwesend erkannt
10:29:44 - Vor 1 Stunde

**Comment by shuntfield** [comment]
![image](https://github.com/audiconnect/audi_connect_ha/assets/63152393/c1473afc-51e4-4602-b79c-a42afcefcdb4)

Mine had been doing this since last night.
Its picked the last two locations I have been at, and doesn't update. I enabled debug logging, but not sure where the log is?

**Comment by moritzmaier84** [comment]
I have this since a few weeks.
Please see #331 
Issue is NOT solved.

Hier is a debug file @Kolbi @coreywillwhat 
[home-assistant_audiconnect_2024-04-19T16-15-02.512Z.log](https://github.com/audiconnect/audi_connect_ha/files/15360400/home-assistant_audiconnect_2024-04-19T16-15-02.512Z.log)

**Comment by coreywillwhat** [comment]
Appreciate everyone's patience.
Thank you for the log @moritzmaier84 .
This looks like the issue in your log, I've seen this before in other logs.
```
2024-04-19 17:49:44.287 ERROR (MainThread) [homeassistant.components.device_tracker] Platform audiconnect does not generate unique IDs. ID Audi A4 Avant Position already exists - ignoring device_tracker.audi_a4_avant_position
```
Need to investigate further.

@Kolbi I believe Unique ID's as you had proposed a while ago would fix this issue.

**Comment by moritzmaier84** [comment]
> Appreciate everyone's patience. Thank you for the log @moritzmaier84 . This looks like the issue in your log, I've seen this before in other logs.
> 
> ```
> 2024-04-19 17:49:44.287 ERROR (MainThread) [homeassistant.components.device_tracker] Platform audiconnect does not generate unique IDs. ID Audi A4 Avant Position already exists - ignoring device_tracker.audi_a4_avant_position
> ```
> 
> Need to investigate further.
> 
> @Kolbi I believe Unique ID's as you had proposed a while ago would fix this issue.

Great news that it's going on and you have ideas for this! Thx!!!

**Comment by ghostwind66** [comment]
I had the same issue as well a few weeks ago. Downgrading to 1.7.0 resolved the issue for me

**Comment by veiter555** [comment]
Thank you Gohstwind66!

After downgrading to Release 1.7.0 it seams to work properly again.

For me the position is crucial due to a Programm that reduces the powerlifting of my house battery if a car is charging at home.

**Comment by moritzmaier84** [comment]
I had this before 1.7.0 and after it.

**Comment by Kolbi** [comment]
Downgrading will also only be a temporary solution as I still believe we didn't changed something crucial since 1.7.0 - it is more installing the new (old) version that it loads the interface / service new. I still think restarting Home-Assistant should do the same thing but maybe in the core there are some caches not erased if not uninstalling / installing the extension.

**Comment by ghostwind66** [comment]
> Downgrading will also only be a temporary solution as I still believe we didn't changed something crucial since 1.7.0 - it is more installing the new (old) version that it loads the interface / service new. I still think restarting Home-Assistant should do the same thing but maybe in the core there are some caches not erased if not uninstalling / installing the extension.

Interestingly enough, I noticed the position not updating on 1.7.0 yesterday as well. A restart fixed the issue. The issue seems to be pretty sporadic and random. This is the first time it has happened since I downgraded a few weeks ago. Strange.

**Comment by coreywillwhat** [comment]
> Downgrading will also only be a temporary solution as I still believe we didn't changed something crucial since 1.7.0 - it is more installing the new (old) version that it loads the interface / service new. I still think restarting Home-Assistant should do the same thing but maybe in the core there are some caches not erased if not uninstalling / installing the extension.

This. No major changes have occurred. I would expect a restart to fix it temporarily as well until we have the actual solution.

**Comment by moritzmaier84** [comment]
> > Downgrading will also only be a temporary solution as I still believe we didn't changed something crucial since 1.7.0 - it is more installing the new (old) version that it loads the interface / service new. I still think restarting Home-Assistant should do the same thing but maybe in the core there are some caches not erased if not uninstalling / installing the extension.
> 
> Interestingly enough, I noticed the position not updating on 1.7.0 yesterday as well. A restart fixed the issue. The issue seems to be pretty sporadic and random. This is the first time it has happened since I downgraded a few weeks ago. Strange.

I agree - it seems to be totally random. I really tried to find some "rules"... but no.

**Comment by ghostwind66** [comment]
I created a script that I can call whenever the need arises (eg. I drive away) that re-enables the device using Spook:

**Comment by Kolbi** [comment]
Maybe similar issue reported here: https://github.com/home-assistant/core/issues/121441

**Comment by pergolafabio** [comment]
Hmm, i see below in log

`2024-07-23 12:55:22.956 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] POSITION: ClientResponseError with status 404 for VIN: *************6552. Error: 404, message='Not Found', url=URL('https://emea.bff.cariad.digital/vehicle/v1/vehicles/XXXX/parkingposition')`

**Comment by TheDelta** [comment]
I have a similar issue where nothing is updated and I have to reload the extension to make it work again.
This was introduced in one of the newer releases, it was working fine after the whole debacle of the new API changes, but now I have to reload it manually once in a while to make it work.

I enabled now debug logging and wait until this happens again (I noticed this multiple times now and reload fixed it all the time).
My logs were filled with this issue (error occurred >1k times) #456 
Might be also related to #330 ?

Is this issue still being worked on?
Anything I can help with?

**Comment by scorbacella** [comment]
Hi, I'm still experiencing the same problem: the Audiconnect platform does not generate unique IDs. Sometimes, it rolls back to the previous position. Reloading the integration updates it to the correct position.
Audi Connect: 1.13.2
HA core-2025.5.3

**Comment by scorbacella** [comment]
Hi, I solved by removing the integration and reinstalling it, assigning a different name to the device.
