### ISSUE TITLE
After Installation via HACS there are only 3 entities available

### ISSUE THREAD

**Issue by mamillion12** [audiconnect/audi_connect_ha#429]
After configuration via HACS and entering my login credentials, there are only three entities available. The Most crucial ones like mileage, fuel level and Trip Data are missing.

**Expected behavior**
Having Access to all other sensor data like mileage, fuel level and single trip data.

**Your Vehicle Details**
Model: Audi A4 Avant 1.4 TFSI
Year: 2017
Type (ICE/PHEV/BEV): B9
I am using an Audi Data Plug to collect the data from the vehicle

**Comment by cdnninja** [comment]
I am not sure this supports those plugs. Does the connect app show the data?

**Comment by mamillion12** [comment]
Yes it does.

**Comment by Kolbi** [comment]
Can you provide a log file?

**Comment by mamillion12** [comment]
[audiconnect_log_ha_28-05-2024.pdf](https://github.com/audiconnect/audi_connect_ha/files/15469330/audiconnect_log_ha_28-05-2024.pdf)

I removed the FIN (vehicle ident) for safety reasons. As I am quite new to home assistant, I am not sure whether such kind of log file is okay. Please let me know in case more information is needed.

**Comment by coreywillwhat** [comment]
Hi @mamillion12 . Thanks for providing more info. Specifically, we would need to see the vehicle data that is returned to understand more about the issues you're seeing. Can you enable debug logging (from integration > audiconnect screen), run the service "Refresh Cloud Data" and then disable debug logging. You will then be given a log file. 

I'm thinking this is a duplicate of #263.

**Comment by coreywillwhat** [comment]
Thank you!

Haven't seen this type of data response before. My understanding is bad gateway errors typically have to do with network configuration or server issues. Has this integration worked for you in the past and this just started occurring? Have you recently made any changes to your network configuration?

**Comment by mamillion12** [comment]
No, it has never worked at any time. All other integrations are working as expected in my Home Assistant instance. Thank you for your support!

**Comment by mamillion12** [comment]
Is there anyone who might be able to support me?

**Comment by Kolbi** [comment]
We would need to capture & analyse data traffic from your app to understand your interfaces.

**Comment by cdnninja** [comment]
To confirm you don't use the Audi connect app for the data but rather another Audi branded one?

**Comment by mamillion12** [comment]
Yes, I am using the Audi connect plug and play app.

**Comment by Kolbi** [comment]
> Yes, I am using the Audi connect plug and play app.

That's good. Now we need data :)

@t0bias-r explained here how he does it with Android: https://github.com/audiconnect/audi_connect_ha/discussions/282#discussioncomment-9060228 - can you provide us something like that?

Do you also see data in https://my.audi.com/ ? Maybe this universal API (with limited data) can also be integrated as fallback.
