### ISSUE TITLE
Position no longer available

### ISSUE THREAD

**Issue by al-exisar** [audiconnect/audi_connect_ha#431]
After updating to 1.9.0, the entity device_tracker.audi_a1_sportback_position is no longer available and i cannot get the position of my car.

This entity is no longer being provided by the audiconnect integration. If the entity is no longer in use, delete it in settings.

**Comment by Kolbi** [comment]
https://github.com/audiconnect/audi_connect_ha/issues/428

**Comment by Kolbi** [comment]
Can you provide any logs? Or do you have the same issues like in #428 ?

**Comment by Kolbi** [comment]
I guess it's the known bug. :)
