### ISSUE TITLE
Services don't work. Lock/unlock, climate control

### ISSUE THREAD

**Issue by ngluvakov** [audiconnect/audi_connect_ha#434]
I can only monitor my car and can't control anything on it. 

I included screenshots of the services that interest me the most. When I call those services, nothing happens afterward. It worked 0% of the time. 

What am I doing wrong? What step did I miss? 

![Screenshot_51](https://github.com/audiconnect/audi_connect_ha/assets/129649324/fbdcbaa4-6d25-4f56-94e5-8a6af91bfc59)
![Screenshot_52](https://github.com/audiconnect/audi_connect_ha/assets/129649324/db0b7c6f-e835-4b0f-9c3d-2cbeaf25405b)

![Screenshot_55](https://github.com/audiconnect/audi_connect_ha/assets/129649324/60eb2526-8db7-4d6e-a0c2-3e9f6282b5f6)
![Screenshot_56](https://github.com/audiconnect/audi_connect_ha/assets/129649324/f5519eb7-29a9-49b1-970f-ed73b7bcc079)

**Comment by shuntfield** [comment]
I have the same, the climate control definately doesn't work and hasn't, for a couple of weeks now.

This error originated from a custom integration.

```
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:307
integration: Audi Connect (documentation, issues)
First occurred: 15:20:37 (1 occurrences)
Last logged: 15:20:37

Unable to start climate control of vehicle wauzxxx6. Error: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZxxx96/climater/actions')
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 307, in start_climate_control
    await self._audi_service.start_climate_control(
  File "/config/custom_components/audiconnect/audi_services.py", line 630, in start_climate_control
    res = await self._api.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_api.py", line 67, in request
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUxxx6/climater/actions')
```

My guess something has been moved at the server end as its not finding the the area to which it needs to adjust. I'm afraid thats where my ability ends with stuff like this!

**Comment by coreywillwhat** [comment]
Unfortunately, I've been experiencing the same thing for a couple weeks. I haven't had time to look into it, and while I'm comfortable making many modifications to the HA side of things. I can't pretend to know what I'm doing on the API side.

@Kolbi @cdnninja 
I've seen @cyr-ius is working hard on a beta, and another user has reported that Audi is using a phased approach to go the authentication for each service. Without someone handling the API side of things, I fear for the longevity we'll be able to keep this going.

**Comment by z3r0bytes** [comment]
Same issue here. Just switched to this integration from the Q4 version of this project (previous versions of this one in december weren't working for the Q4). "https://github.com/moritzwiechers/audi_connect_ha_q4"

Now after migrating it gives more information then the fork from moritz, but also their, the climate control didn't work. 
Climiate control via the app does work. 

`Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:307
integration: Audi Connect ([documentation](https://github.com/audiconnect/audi_connect_ha), [issues](https://github.com/audiconnect/audi_connect_ha/issues))
First occurred: 23:28:42 (2 occurrences)
Last logged: 23:29:19

Unable to start climate control of vehicle wauzzzfz0rp030589. Error: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZZZFZ*********/climater/actions')
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 307, in start_climate_control
    await self._audi_service.start_climate_control(
  File "/config/custom_components/audiconnect/audi_services.py", line 630, in start_climate_control
    res = await self._api.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_api.py", line 67, in request
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZZZFZ*********/climater/actions')`

**Comment by cdnninja** [comment]
> Unfortunately, I've been experiencing the same thing for a couple weeks. I haven't had time to look into it, and while I'm comfortable making many modifications to the HA side of things. I can't pretend to know what I'm doing on the API side.
> 
> @Kolbi @cdnninja I've seen @cyr-ius is working hard on a beta, and another user has reported that Audi is using a phased approach to go the authentication for each service. Without someone handling the API side of things, I fear for the longevity we'll be able to keep this going.

I will see if I can sniff the endpoint. I haven't done it for audi before but have for both Kia and Yoto.

**Comment by gomble** [comment]
same problem:
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car

**Comment by acdcnow** [comment]
same here :
This error originated from a custom integration.

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:307
integration: Audi Connect (documentation, issues)
First occurred: 16:18:19 (1 occurrences)
Last logged: 16:18:19

Unable to start climate control of vehicle xxxxx. Error: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/xxx/vehicles/xxxxxx/climater/actions')
Traceback (most recent call last):
  File "/config/custom_components/audiconnect/audi_connect_account.py", line 307, in start_climate_control
    await self._audi_service.start_climate_control(
  File "/config/custom_components/audiconnect/audi_services.py", line 630, in start_climate_control
    res = await self._api.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/audiconnect/audi_api.py", line 67, in request
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/xxx/vehicles/XXXX/climater/actions')

**Comment by pergolafabio** [comment]
I have my Q4 next week, is this still an ongoing issue? Has someone sniffed the app yet to get the correct url?

**Comment by pergolafabio** [comment]
did some tracing:

if i test climate in HA, it fails with below:
`
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/DE/vehicles/xxxx/climater/actions')`

i checked/traced:
i see this in httptoolkit:

`https://emea.bff.cariad.digital/vehicle/v1/vehicles/xxx/climatisation/start`

with request

```
{
  "targetTemperature": 22,
  "targetTemperatureUnit": "celsius",
  "climatisationWithoutExternalPower": true,
  "climatizationAtUnlock": false,
  "windowHeatingEnabled": false,
  "zoneFrontLeftEnabled": false,
  "zoneFrontRightEnabled": false,
  "zoneRearLeftEnabled": false,
  "zoneRearRightEnabled": false
}
```

for stop:

`https://emea.bff.cariad.digital/vehicle/v1/vehicles/xxx/climatisation/stop`

Maybe we can start a seperate issue , so i can provide more details about other stuff maybe?

**Comment by cdnninja** [comment]
Could you trace similar for lock unlock?

**Comment by pergolafabio** [comment]
> Could you trace similar for lock unlock?

I have a Q4, it doesn't support lock/unlock :-(

**Comment by pergolafabio** [comment]
maybe this can be closed, since its a duplicate ticket?

**Comment by Kolbi** [comment]
closed go on here with lock&unlock: https://github.com/audiconnect/audi_connect_ha/issues/433

**Comment by gomble** [comment]
climate does not work, i am getting:

aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url='https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/climatisation/v1/Audi/DE/vehicles/WAUZZZFZXRPXXXXXX/climater/actions'
