### ISSUE TITLE
Range no longer available 

### ISSUE THREAD

**Issue by GMTheDoctor** [audiconnect/audi_connect_ha#437]
Hi Everyone,

as I said in the title, the sensor range is no longer available and even the others similar doesn't work anymore. Is it a known bug? (All the other sensors are normally working) Thank you in advance for the help.

- Audi Q3 2023 S-Tronic Business Edition (Diesel)

![image](https://github.com/audiconnect/audi_connect_ha/assets/82093488/92d46618-038c-405a-9d03-d9b29aad6535)

**Comment by Morgoth67** [comment]
> Hi Everyone,
> 
> as I said in the title, the sensor range is no longer available and even the others similar doesn't work anymore. Is it a known bug? (All the other sensors are normally working) Thank you in advance for the help.
> 
> * Audi Q3 2023 S-Tronic Business Edition (Diesel)
> 
> ![image](https://private-user-images.githubusercontent.com/82093488/341987727-92d46618-038c-405a-9d03-d9b29aad6535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTk1NjIsIm5iZiI6MTcxOTU1OTI2MiwicGF0aCI6Ii84MjA5MzQ4OC8zNDE5ODc3MjctOTJkNDY2MTgtMDM4Yy00MDVhLTlkMDMtZDliMjlhYWQ2NTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA3MjEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZmQxNTE0NzFiN2IzZDU0M2QyMzE4ZTEzYzJjNzVmYzBjNzkyOGU4ZWRlZGE3ZDM4N2RmMTM2N2ZlZGZkOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e7t8cJvR9akBJ9oMArA4owpFdMjK_6nbd6aO7jMDQ2g)



Is this still happening? It works for me, the three of them.

**Comment by GMTheDoctor** [comment]
Sorry I don't know how to close the thread. It started working again without doing nothing thank you :)
