### ISSUE TITLE
LOGIN: Login to Audi service failed: 'NoneType' object has no attribute 'get' after HA update to 2024.7.3

### ISSUE THREAD

**Issue by yufretti** [audiconnect/audi_connect_ha#444]
Hi,
after HA update, Audi Connect does not work any more.
I see this in my log:

Registratore: custom_components.audiconnect.audi_connect_account
Fonte: custom_components/audiconnect/audi_connect_account.py:75
Integrazione: Audi Connect ([documentazione](https://github.com/audiconnect/audi_connect_ha), [problemi](https://github.com/audiconnect/audi_connect_ha/issues))
Prima occorrenza: 11:25:35 (2 occorrenze)
Ultima registrazione: 11:26:05
LOGIN: Login to Audi service failed, trying again in 10 seconds

Registratore: custom_components.audiconnect.audi_connect_account
Fonte: custom_components/audiconnect/audi_connect_account.py:90
Integrazione: Audi Connect ([documentazione](https://github.com/audiconnect/audi_connect_ha), [problemi](https://github.com/audiconnect/audi_connect_ha/issues))
Prima occorrenza: 11:26:16 (1 occorrenze)
Ultima registrazione: 11:26:16
LOGIN: Login to Audi service failed: 'NoneType' object has no attribute 'get'

Registratore: custom_components.audiconnect.audi_account
Fonte: custom_components/audiconnect/audi_account.py:182
Integrazione: Audi Connect ([documentazione](https://github.com/audiconnect/audi_connect_ha), [problemi](https://github.com/audiconnect/audi_connect_ha/issues))
Prima occorrenza: 11:26:16 (1 occorrenze)
Ultima registrazione: 11:26:16
Failed refresh cloud data

Thanks.
Yuri

**Comment by cdnninja** [comment]
Did this recover on its own?

**Comment by yufretti** [comment]
It started working again after reloading the Audi Connect integration and restarting HA
