### ISSUE TITLE
Basically nothing is working anymore

### ISSUE THREAD

**Issue by menloperk** [audiconnect/audi_connect_ha#454]
**Describe the bug**
What on earth has happened with this integration? After having zero updates for a few week I decided to reinstall it and now I am only left with 10 entities? This integration seems totally broken.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logfile**
How to enable audiconnect debugging?
Settings > Integrations > Audi Connect > Enable Debug Logging
Run service refresh_cloud_data
Disable Debug Logging

**Your Vehicle Details**
Model:
Year:
Type (Gas/Hybrid/Electric):
Region (EU/US/CA/CN):

**Comment by cdnninja** [comment]
Please complete the template without detail we can't help.

**Comment by coreywillwhat** [comment]
@menloperk we're doing our best to keep this functioning as best we can, but note none of us are paid to do this, we have full time jobs, families, and personal lives. We also rely on users raising issues for us to understand what is working or what is broken. 

As @cdnninja has suggested, please provide more details about what you have available, what is missing, your vehicle details, and region. A log file during a refresh cloud data service call would also be helpful.

The Audi API changes several times a year and we do our best to keep up with it.

**Comment by moritzmaier84** [comment]
I lost all my entities to "unknown" today, too.
But also I have some little errors in the Audi App.
So maybe there's a generel problem with the Audi API?
How about the others here?

**Comment by coreywillwhat** [comment]
503 makes me think there is an Audi Server issue.
Checking [here ](https://updownradar.com/status/my.audi.com) I see there is an uptick in issues for the EU.

**Comment by moritzmaier84** [comment]
> 503 makes me think there is an Audi Server issue. Checking [here ](https://updownradar.com/status/my.audi.com) I see there is an uptick in issues for the EU.

Also:

Logger: custom_components.audiconnect.audi_connect_account
Quelle: custom_components/audiconnect/audi_connect_account.py:660
Integration: Audi Connect ([Dokumentation](https://github.com/audiconnect/audi_connect_ha), [Probleme](https://github.com/audiconnect/audi_connect_ha/issues))
Erstmals aufgetreten: 17:02:18 (1 Vorkommnisse)
Zuletzt protokolliert: 17:02:18

POSITION: ClientResponseError with status 502 for VIN: *************9780. Disabling vehicle position support.

**Comment by coreywillwhat** [comment]
502 bad gateway means there is an upstream issue. This could be local, or with audi servers. Again, I believe this is related to the uptick in issues with Audi Servers in the EU.

**Comment by moritzmaier84** [comment]
> 502 bad gateway means there is an upstream issue. This could be local, as in your local router, ISP, DNS etc, or with audi servers. Again, I believe this is related to the uptick in issues with Audi Servers in the EU.

Thx! I'll checkt later and keep you updated.

**Comment by coreywillwhat** [comment]
note, 502 error currently disables the specific service (position in your case) until the next HA reboot or Audiconnect integration restart.

This will be fixed in the next release.

**Comment by coreywillwhat** [comment]
Adding to this, US Region Service Calls aren't working at the moment either.

**Comment by menloperk** [comment]
Everything seems back to normal again. Same for my VW integration. I guess this all had to do with a service unavailable at VW / Audi. Thanks all!
