### ISSUE TITLE
Status 502 while updating `preheater`

### ISSUE THREAD

**Issue by mm98** [audiconnect/audi_connect_ha#458]
**Describe the bug**
Since the [last update](https://github.com/audiconnect/audi_connect_ha/releases/tag/v1.10.1) I've started seeing this. Isn't really a problem for me. Only reporting this because the error states that I should.

```
This error originated from a custom integration.

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:822
integration: Audi Connect (documentation, issues)
First occurred: July 29, 2024 at 10:02:39 (80 occurrences)
Last logged: 05:47:39

PREHEATER: ClientResponseError with status 502 while updating preheater for VIN: *************1567. This issue may resolve in time. If it persists, please open an issue.
```

**To Reproduce**
None

**Expected behavior**
My car doesn't support preheating. So this shouldn't be enabled I guess?

**Screenshots**
None

**Logfile**
[home-assistant_audiconnect_2024-07-30T04-09-06.178Z.log](https://github.com/user-attachments/files/16421916/home-assistant_audiconnect_2024-07-30T04-09-06.178Z.log)

**Your Vehicle Details**
Model: A5 Sportback advanced 40 TFSI S tronic
Year: 2021
Type (Gas/Hybrid/Electric): Gas
Region (EU/US/CA/CN): EU

**Comment by pergolafabio** [comment]
i'm seeing the same, with Q4 Etron,

**Comment by zimbo86** [comment]
same here, A4 B9

**Comment by over40** [comment]
Same here: Audi Q3
2024-07-31 09:57:14.649 WARNING (MainThread) [custom_components.audiconnect.audi_connect_account] PREHEATER: ClientResponseError with status 502 while updating preheater for VIN: ****. This issue may resolve in time. If it persists, please open an issue.

**Comment by woopstar** [comment]
Same here. Also getting it.

**Comment by chris2div** [comment]
Same issue with an Audi  Q4 etron.

**Comment by olanystrom** [comment]
Same error here.
Q4 e-tron 45 e-tron quattro (2024)
