### ISSUE TITLE
2 devices while only has 1 car and can't delete the bad one

### ISSUE THREAD

**Issue by lfarkas** [audiconnect/audi_connect_ha#460]
In my case it shows 2 devices (while only has 1 car) and 80 entities while half of these are "not provided". the problem is that i'm not able to delete the wrong device (called "Oil change time" ???)
So is there any solution for this?

**Comment by cbailster** [comment]
I've just started experiencing this issue today. It's been working fine until at most 48hrs ago (haven't updated HA or Audi-Connect integration since last month), and now I've got 2 cars showing up. My original car has all sensors showing "Unknown" whilst I've now got an RS Q3 (which I don't own) showing up which does seem to be pulling data

**Comment by woopstar** [comment]
I also have the RS Q3 in my list. Tried deleting the integration and set it up again, and just got the RS Q3 again. So I think there is some issues with the Audi API once again.

**Comment by cdnninja** [comment]
Yes my native app shows two as well.

**Comment by Homas** [comment]
Looks like they fixed the issue. My "original" car started getting information.

**Comment by coreywillwhat** [comment]
was this resolved?

**Comment by lfarkas** [comment]
i still have an "Oil change time" device and there is no way (at least i can't find) to delete it.

**Comment by cbailster** [comment]
Still broken for me. I'm now only seeing one car, with the right model details again, but I'm only getting 4 entities, and they're not being updated - see screenshot
<img width="334" alt="Screenshot 2024-08-28 at 14 24 41" src="https://github.com/user-attachments/assets/36a6ad67-fd22-4a33-8aa7-6f339aef0010">

**Comment by coreywillwhat** [comment]
> Still broken for me. I'm now only seeing one car, with the right model details again, but I'm only getting 4 entities, and they're not being updated - see screenshot <img alt="Screenshot 2024-08-28 at 14 24 41" width="334" src="https://private-user-images.githubusercontent.com/173260/362298501-36a6ad67-fd22-4a33-8aa7-6f339aef0010.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTM1MDcsIm5iZiI6MTcyNDg1MzIwNywicGF0aCI6Ii8xNzMyNjAvMzYyMjk4NTAxLTM2YTZhZDY3LWZkMjItNGEzMy04YWE3LTZmMzM5YWVmMDAxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMzUzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTExYmM3NDQ1NzEyMjQ5Y2QxNzg5NDZjZjlkYzg1YzgwODgxN2IwODU1MjhlZGViZWQ1NTJmMjdmNDc4NWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XByVUgKrkTbSY8TOGYhf-qX6Rqkv1lZNVVgBg6jqwGg">

Can you open a new issue for this. With it can you provide logs during an `refresh_cloud_data` service call?

**Comment by Homas** [comment]
All sensors works for me with Q7. I didn't try to lock/unlock.
The annoying part is that I can't delete the "bad vehicle" w/o removing and reinstalling the integration.

**Comment by cbailster** [comment]
@coreywillwhat - Creating the debug logs when calling refresh_cloud_data showed what the actual problem was - the account I was using had become unverified (but somehow still linked) to the car. Had to fiddle around a lot with account settings on the my.audi.com site, but looks like it's all working correctly again now.

**Comment by coreywillwhat** [comment]
> @coreywillwhat - Creating the debug logs when calling refresh_cloud_data showed what the actual problem was - the account I was using had become unverified (but somehow still linked) to the car. Had to fiddle around a lot with account settings on the my.audi.com site, but looks like it's all working correctly again now.

Great news! Glad you got the sensor data working again.

**Comment by coreywillwhat** [comment]
> All sensors works for me with Q7. I didn't try to lock/unlock. The annoying part is that I can't delete the "bad vehicle" w/o removing and reinstalling the integration.

I wouldn't expect any functions to work at this time, but glad the Q7 sensor data is working. I never had the duplicate car issue, so I'm unable to debug that.

That said, i frequently delete and re-add the integration for development work. I dont find it too cumbersome, but i just use the given device name so i dont have to redo any HA dashboards/automations.

**Comment by Homas** [comment]
> I dont find it too cumbersome, but i just use the given device name so i dont have to redo any HA dashboards/automations.

Yep, but you lose all stats (I'm not sure actually if there any long term stats saved by default).
