### ISSUE TITLE
LOGIN: Login to Audi service failed: 'client_id'

### ISSUE THREAD

**Issue by githubsharezone** [audiconnect/audi_connect_ha#462]
**Describe the bug**
i dont modify nothing and now show a messages 

LOGIN: Login to Audi service failed: 'client_id'

i try remove and changed password but nothing not function

**Comment by leifMatt** [comment]
I got the same issue with same login meessage. Tried to inactivate followed by activate and reconfigure. No error message after but all sensors unavailable.

**Comment by githubsharezone** [comment]
I tried to follow your advice but still the same error

**Comment by Homas** [comment]
It didn't work for me since early last week, it started working on Saturday or Sunday and stopped working again.
Most likely related with the RS Q3 issue (I've reported it to a dealer on Saturday).

**Comment by martijncas** [comment]
client_id error here also since a couple of hours. Tried to disable / enable and reinstalled. No luck.

**Comment by andreabafile** [comment]
same here, it looks like it's a wide issue then.

**Comment by menloperk** [comment]
I know it doesn't really help but exactly the same issue here...

**Comment by githubsharezone** [comment]
I tried now but it still gives authentication error. in the logs but I no longer see the client_ID error. I can't understand what it could be

**Comment by JimRnewell** [comment]
i have the same issue

**Comment by mm98** [comment]
I started working by me again. I removed the integration and added it again and it worked.

**Comment by JimRnewell** [comment]
just reloaded vthe integration and it nowrks for me again

**Comment by martijncas** [comment]
confirming that it started to work again after reloading the integration

**Comment by githubsharezone** [comment]
confirm that now is ok

**Comment by shuntfield** [comment]
Confirmed: not working here.

Reload doesn't work, and I have removed and re-added the integration and it comes back "invalid credentials"

Hasn't worked for a couple of days, and still isn't.

**Comment by Homas** [comment]
It works for me and they fixed the car!!!!

**Comment by githubsharezone** [comment]
My integration work without problem Il giorno 21 ago 2024, alle ore 03:14, Vadim ***@***.***> ha scritto:﻿
It works for me and they fixed the car!!!!
