### ISSUE TITLE
Continuous warning logs. 

### ISSUE THREAD

**Issue by junaidsurve** [audiconnect/audi_connect_ha#465]
Every requests results in the following Warning - 
PREHEATER: ClientResponseError with status 502 while updating preheater for VIN: 

**To Reproduce**
Just basic installation. A valid username and password. No S-PIN.

**Expected behavior**
No warnings.

**Logfile**
This error originated from a custom integration.

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:822
integration: Audi Connect (documentation, issues)
First occurred: 2:14:04 PM (1 occurrences)
Last logged: 2:14:04 PM

PREHEATER: ClientResponseError with status 502 while updating preheater for VIN: *************ABCD. This issue may resolve in time. If it persists, please open an issue.

**Your Vehicle Details**
Model: Q4 eTron
Year: 2023
Type (Gas/Hybrid/Electric): Electric
Region (EU/US/CA/CN): DE

**Comment by coreywillwhat** [comment]
#466
