### ISSUE TITLE
PREHEATER: ClientResponseError with status 502 while updating preheater

### ISSUE THREAD

**Issue by BobC76** [audiconnect/audi_connect_ha#467]
**Describe the bug**
> This error originated from a custom integration.
> 
> Logger: custom_components.audiconnect.audi_connect_account
> Source: custom_components/audiconnect/audi_connect_account.py:822
> integration: Audi Connect (documentation, issues)
> First occurred: 18:28:20 (1 occurrences)
> Last logged: 18:28:20
> 
> PREHEATER: ClientResponseError with status 502 while updating preheater for VIN: *************3442. This issue may resolve in time. If it persists, please open an issue.
> 
It persists...

**To Reproduce**
Set up the integration with a UK Q4 etron (1st edition, in case that is relevant).  Get lots of entities. Check the logs, see this warning.

**Expected behavior**
Not clear what the expected behaviour is but this model doesn't have a preheater. The integration also creates a door lock switch but I don't think that is supported via the myaudi app/for this model. It is possible to set the target charge and set timers and set up and start climate control via the myaudi app though those aren't available via this integration. So I suspect some mismatch between the expected and actual options available for this particular model.

**Screenshots**
na

**Logfile**
[audi-connect-log.txt](https://github.com/user-attachments/files/16787098/audi-connect-log.txt)

**Your Vehicle Details**
Model: q4 etron
Year: 2021
Type (Gas/Hybrid/Electric): Electric
Region (EU/US/CA/CN): UK

**Comment by pergolafabio** [comment]
will be fixed in new version, a PR is already submitted, you can close this one
