### ISSUE TITLE
Error in HA log after deleting component

### ISSUE THREAD

**Issue by Kydix** [audiconnect/audi_connect_ha#469]
I have error in HA logs even after deleting Audi Connect component

> Enregistreur: custom_components.audiconnect.audi_connect_account
> Source: custom_components/audiconnect/audi_connect_account.py:680
> intégration: Audi Connect (documentation, problèmes)
> S'est produit pour la première fois: 17:55:04 (4 occurrences)
> Dernier enregistrement: 18:40:02
> 
> POSITION: ClientResponseError with status 400 for VIN: *************6849. Error: 400, message='Bad Request', url='https://emea.bff.cariad.digital/vehicle/v1/vehicles/WAUZZZ8X7FB026849/parkingposition'
> 
>

**Comment by pergolafabio** [comment]
that means its not uninsalled correctly, try to remove device again, reboot HA, then detele also the HACS component, reboot HA again
