### ISSUE TITLE
Sync not working with 2024.10.0b

### ISSUE THREAD

**Issue by Pastaloverzzz** [audiconnect/audi_connect_ha#472]
The Audi app can't refresh with the new core beta (2024.10.b0). (I have a new model so i couldn't open/close doors of start/stop charging dus to other errors but now i can't even see my entity States because of the following errors in the logs.

Logger: custom_components.audiconnect.audi_connect_account
Bron: custom_components/audiconnect/audi_connect_account.py:90
integratie: Audi Connect (documentatie, problemen)
Eerst voorgekomen: 20:58:15 (3 gebeurtenissen)
Laatst gelogd: 21:15:17

LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=91b4426c72bea4abf32b7afe7ce7a2d03ed84d80&canChangeCountryOfResidence=true
LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=73b91d6aa26a4b7e78aa870faa0cd7c0cc845c50&canChangeCountryOfResidence=true
LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=0da0879e0b14d0ff303f75eb102625044aeef4c9&canChangeCountryOfResidence=true

**Your Vehicle Details**
Model: Q4 e-tron
Year: 2024
Type (Gas/Hybrid/Electric): electric
Region (EU/US/CA/CN): EU

**Comment by pergolafabio** [comment]
My integration is failed too, reloading doesn't help, also Q4 owner here... 2024.9 RLS...

Open/close is not possible on Q4 models, also start climate doesn't work yet with this integration...
But the component should load the entities

**Comment by pergolafabio** [comment]
i checked my logs, and i see the same error indeed

**Comment by pergolafabio** [comment]
ok, fixed for me, you need to logout from the myAudi app on your phone, then login, accept the new terms and conditions, after that ,reload this integration

**Comment by Pastaloverzzz** [comment]
This fixed it for me as well! Thanks 🙏

**Comment by nobirdnobird** [comment]
Relogin in App works 4 me 2.
I have to agree New data privacy rules. After I agree the HA integration works like bevore.
