### ISSUE TITLE
Car location gone 

### ISSUE THREAD

**Issue by TheRaver13** [audiconnect/audi_connect_ha#474]
**Describe the bug**
Since a few days i saw that the car location entity is gone. My old entity was not working anymore and I saw that there was a second integration and that did not have the location anymore "Entity not available: device_tracker.audi_q7_suv_position".

**Logfile**
How to enable audiconnect debugging?
Settings > Integrations > Audi Connect > Enable Debug Logging
Run service refresh_cloud_data
Disable Debug Logging

**Your Vehicle Details**
Model: Q7
Year: 2020
Type (Hybrid):
Region (EU:

**Comment by niilorm** [comment]
See #475
