### ISSUE TITLE
HA component not function Invalid credential

### ISSUE THREAD

**Issue by githubsharezone** [audiconnect/audi_connect_ha#475]
This morning I realized that I was no longer receiving information about my car Q5. I tried to delete and reinstall the component but it returns invalid credential. Anyone have the same problem as me? From the AUdi website everything works normally

**Comment by pergolafabio** [comment]
Do you also see this in your log?

```
2024-09-27 09:37:46.548 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Login to Audi service failed, trying again in 10 seconds
2024-09-27 09:37:57.344 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Login to Audi service failed: /signin-service/v1/0XXX@apps_vw-dilab_com/terms-and-conditions?relayState=XXXX&canChangeCountryOfResidence=true
2024-09-27 09:37:57.345 WARNING (MainThread) [custom_components.audiconnect.audi_account] Failed refresh cloud data
```

**Comment by githubsharezone** [comment]
ogger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:90
integration: Audi Connect ([documentation](https://github.com/audiconnect/audi_connect_ha), [issues](https://github.com/audiconnect/audi_connect_ha/issues))
First occurred: 7:59:40 AM (15 occurrences)
Last logged: 9:36:43 AM

LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=9d070e8a108eb41fd6618b671befd539e935432b&canChangeCountryOfResidence=true
LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=3d37f356a6ccc9cabdc8b057b1eeeb4d7b73a223&canChangeCountryOfResidence=true
LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=0cce27bcbe3f3f92221f2135f9b12a97f6f0fe7b&canChangeCountryOfResidence=true
LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=cbca5ffa30fab89eb61c47e2176f71bf3b178d91&canChangeCountryOfResidence=true
LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/terms-and-conditions?relayState=18c230680754b2cfacaf51ea4d0077ce85e3b196&canChangeCountryOfResidence=true

**Comment by pergolafabio** [comment]
ok, fixed for me, you need to logout from the myAudi app on your phone, then login, accept the new terms and conditions, after that ,reload this integration

**Comment by githubsharezone** [comment]
Your advice worked for me too. thanks for the support

**Comment by ghostwind66** [comment]
I can also confirm that this fix works.

**Comment by ps915** [comment]
I can also confirm. After logging out, log in  accept terms and my Q5 sends data again! 🍻

**Comment by zimbo86** [comment]
thanks, worked for me too.

**Comment by helmut-hackl** [comment]
Thank you, saved me a lot of time and works as described!

**Comment by GMTheDoctor** [comment]
> ok, fixed for me, you need to logout from the myAudi app on your phone, then login, accept the new terms and conditions, after that ,reload this integration

Worked for me! Thank you so much man

**Comment by Devlin-151023** [comment]
Worked for me too - thanks for the help!

**Comment by danoev** [comment]
Monday 30th September @ 12:04

I had this same issue as above and followed the steps as others have, that issue is now resolved but I am now getting the following error returned in the logs:

> LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=94dfbf32e3eb4096ef9835c42b339c9a71c1cfe4&nextButtonDisabled=true&enableNextButtonAfterSeconds=32&error=login.error.throttled

- I have logged out of the Audi mobile app, then logged back in to confirm the password is correct.
- I removed the integration from HA then set up again as new.  HA states the setup was successful but the above error stops the intergration from initialising fully and all entities remain unavailable.

**Comment by simonepittis** [comment]
unfortunately this is the millionth time that AUDI has problems with the servers. unfortunately there is no choice but to wait for them to solve the problem... until next time

**Comment by danoev** [comment]
> unfortunately this is the millionth time that AUDI has problems with the servers. unfortunately there is no choice but to wait for them to solve the problem... until next time

Thanks for your reply!

I did think this but then thought it could be isolated but at least if others have similar error they now know it is server related.  Good old Audi...  I will wait for it to spring into life at some point in the future...

**Comment by simonepittis** [comment]
FYI:
![image](https://github.com/user-attachments/assets/41b98fb0-fa93-4deb-b2df-3aaea852100a)

Error on Server Gateway.... like AUDI constant error

**Comment by niilorm** [comment]
> Monday 30th September @ 12:04
> 
> I had this same issue as above and followed the steps as others have, that issue is now resolved but I am now getting the following error returned in the logs:
> 
> > LOGIN: Login to Audi service failed: /signin-service/v1/09b6cbec-cd19-4589-82fd-363dfa8c24da@apps_vw-dilab_com/login/authenticate?relayState=94dfbf32e3eb4096ef9835c42b339c9a71c1cfe4&nextButtonDisabled=true&enableNextButtonAfterSeconds=32&error=login.error.throttled
> 
>     * I have logged out of the Audi mobile app, then logged back in to confirm the password is correct.
> 
>     * I removed the integration from HA then set up again as new.  HA states the setup was successful but the above error stops the intergration from initialising fully and all entities remain unavailable.

I'd disable the integration and try later. Audi is quite quick to throttle queries. Not so long ago you'd get 429s with just setting the poll interval to 10 or so minutes.

**Comment by zenyagami** [comment]
It also worked for me, logging out from Audi app and accepting the "new terms and conditions" OMG with the audi developers, it works not, thanks for the suggestion!!!

**Comment by coreywillwhat** [comment]
This issue seems resolved. Please let me know if it needs to be reopened

**Comment by pergolafabio** [comment]
I would leave this one open for a while, so other people know what Todo ... Maybe a clean up on this thread is needed :-)

**Comment by ZenoBell** [comment]
After logging in and out of the app, accepting the terms, and reloading the integration, everything started working perfectly. Thank you!

**Comment by nicoske** [comment]
Found this issue after I solved it already by connecting to the "myaudi" website and accept the new terms, probably easier than logout/login from app.
