### ISSUE TITLE
DataPlug Connection with Home Assistant

### ISSUE THREAD

**Issue by itspuia** [audiconnect/audi_connect_ha#477]
Hello and thank you for your great Integration!

When I read about this a couple of months ago, I bought the "DataPlug" to make older models (2013 Audi A1) smarter. I read somewhere, that this would work with this Integration.
Unfortunately I do not understand, how to connect the Audi connect plug and play App with the MyAudi ID, from where this integration gets its data. Do you by any chance know how to make the connection so that I can see my car stats from the Audi DataPlug?

Thank you very much!

**Comment by Kolbi** [comment]
Maybe @JoLukas can assist? We seems to use it with the App properly: https://github.com/audiconnect/audi_connect_ha/issues/479
