### ISSUE TITLE
Integration fails to start - Login to Audi service failed: 'Location'

### ISSUE THREAD

**Issue by xathon** [audiconnect/audi_connect_ha#482]
**Describe the bug**
The integration fails to start. The logs show "LOGIN: Login to Audi service failed, trying again in 10 seconds" and then "Login to Audi service failed: 'Location'".

**To Reproduce**

1. Try to use integration
2. See error

**Expected behavior**
The integration should load.

**Screenshots**
n/a

**Logfile**
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.audiconnect.audi_connect_account
Quelle: custom_components/audiconnect/audi_connect_account.py:90
Integration: Audi Connect (Dokumentation, Probleme)
Erstmals aufgetreten: 15. Oktober 2024 um 21:37:04 (86 Vorkommnisse)
Zuletzt protokolliert: 17:30:17

LOGIN: Login to Audi service failed: 'Location'
```
**Your Vehicle Details**
Model: A4
Year: 2023
Type (Gas/Hybrid/Electric): Gas
Region (EU/US/CA/CN): EU

**Comment by t0bias-r** [comment]
A dialog for consenting to data processing blocks the login.

Log out and log in again in the mobile app. When logging in again, the dialog that must be confirmed appears on the mobile.
The automatic login of the script then works again.

**Comment by xathon** [comment]
Huh, so I actually saw that dialogue a few days ago, but it didn't actually work until I logged out and back in again. Thanks!
