### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by jonny190** [audiconnect/audi_connect_ha#488]
**Describe the bug**
Cannot login to plugin after it working for months

**To Reproduce**
add plugin and try to login 

**Expected behavior**
To login and pull sensors

**Screenshots**
n/a

**Logfile**
2024-11-01 19:31:09.895 DEBUG (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Requesting login to Audi service...
2024-11-01 19:31:09.895 DEBUG (MainThread) [custom_components.audiconnect.audi_services] LOGIN: Starting login to Audi service...
2024-11-01 19:31:14.955 DEBUG (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Requesting login to Audi service...
2024-11-01 19:31:14.956 DEBUG (MainThread) [custom_components.audiconnect.audi_services] LOGIN: Starting login to Audi service...

**Your Vehicle Details**
Model: Etron 55 Quattro
Year: 2019
Type (Gas/Hybrid/Electric): Electric
Region (EU/US/CA/CN): EU

**Comment by cdnninja** [comment]
Can you login using the native app?

**Comment by N3rdix** [comment]
The native App is working for me, but the Integration stoppen working yesterday Morning.

```
Logger: custom_components.audiconnect.audi_connect_account
Quelle: custom_components/audiconnect/audi_connect_account.py:90
Integration: Audi Connect (Dokumentation, Probleme)
Erstmals aufgetreten: 2. November 2024 um 20:10:23 (106 Vorkommnisse)
Zuletzt protokolliert: 09:18:47

LOGIN: Login to Audi service failed: 'Timeout' object does not support the context manager protocol
```

```
Logger: custom_components.audiconnect.audi_connect_account
Quelle: custom_components/audiconnect/audi_connect_account.py:75
Integration: Audi Connect (Dokumentation, Probleme)
Erstmals aufgetreten: 2. November 2024 um 20:10:03 (212 Vorkommnisse)
Zuletzt protokolliert: 09:18:37

LOGIN: Login to Audi service failed, trying again in 10 seconds
```

**Comment by jonny190** [comment]
Yeah, the native app works fine for me... However when signing in to the app I noticed my password manager didn't prompt to auto fill (bitwarden) 

Then I logged in, it prompted me to save fresh credentials for a different URL (VW related) not sure if there may have been a change the app was prepared for?

**Comment by Jabei1969** [comment]
Same for me. Native app is fine but can’t now log into HA integration

**Comment by eskholm** [comment]
Same issue here. 

2024-11-04 10:28:06.690 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Login to Audi service failed, trying again in 10 seconds
2024-11-04 10:28:16.692 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Login to Audi service failed, trying again in 10 seconds
2024-11-04 10:28:26.693 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] LOGIN: Login to Audi service failed: 'Timeout' object does not support the context manager protocol
2024-11-04 10:28:26.693 WARNING (MainThread) [custom_components.audiconnect.audi_account] Failed refresh cloud data

**Comment by minosrex** [comment]
Also cannot login anymore, says my credentials are not valid.

**Comment by gomble** [comment]
same

**Comment by andrewbuckingham** [comment]
I had a similar problem a week ago or so. Tried removing and re-adding the HA integration; couldn't get it to sign in.

But, I noticed it coincided with Audi changing the T&Cs. It required me to go into the native app and view the T&Cs, then accept them again. Once I'd done that, the HA integration worked again. This is with an Etron 55 quattro 2022. Might just be coincidence, of course.

**Comment by jonny190** [comment]
@andrewbuckingham I had the same a few weeks ago, thats when i tried logging out and back in to the app just in case it was the same again. 

Thats when i noticed my password manager no longer autofilled and prompted me to save the credentials again previously it was saved as 
de.myaudi.mobile.assistant

now its saving as 
uk.co.volkswagen.myvw

**Comment by minosrex** [comment]
> I had a similar problem a week ago or so. Tried removing and re-adding the HA integration; couldn't get it to sign in.
> 
> But, I noticed it coincided with Audi changing the T&Cs. It required me to go into the native app and view the T&Cs, then accept them again. Once I'd done that, the HA integration worked again. This is with an Etron 55 quattro 2022. Might just be coincidence, of course.

Same here, connection is now re-established.

**Comment by N3rdix** [comment]
No luck with my Q4, I already accepted some new EULAs a few weeks ago when the integration was still working fine.
Seems not to be the root cause, or not the only one 😀

**Comment by korsmann** [comment]
> I had a similar problem a week ago or so. Tried removing and re-adding the HA integration; couldn't get it to sign in.
> 
> But, I noticed it coincided with Audi changing the T&Cs. It required me to go into the native app and view the T&Cs, then accept them again. Once I'd done that, the HA integration worked again. This is with an Etron 55 quattro 2022. Might just be coincidence, of course.

This actually worked for me as well.  E-tron MY 2019.  Had to log out of the app, back in, confirm T&Cs, log back in with HA.

**Comment by menloperk** [comment]
For me this is broken... logging out and back in in the app doesn't have any effect. Also deleteing the integration and trying to configure it back again, doesn't help either... I immediately get 'invalid credentials'.  Before deleting the integration I had this in the logs:
LOGIN: Login to Audi service failed: 'Timeout' object does not support the context manager protocol

**Comment by N3rdix** [comment]
I just tried to add my account into a dev container instance and this worked without any issues. In my productive environment it is still giving the invalid credentials error, it seems like it doesn't try to login at all.

Could this be some abandoned cache somewhere? Couldn't find anything in my config folder so far...

**Comment by jonny190** [comment]
I've tried uninstalling the plugin, restarting and then reinstalling but still the same error. But it could be cached elsewhere, good shout

**Comment by N3rdix** [comment]
I found the issue 🥳 I will submit a PR this evening and hopefully someone can merge it.

If anyone volunteers to test this locally upfront by replacing source files let me know. I'll then share the details

**Comment by eskholm** [comment]
> I found the issue 🥳 I will submit a PR this evening and hopefully someone can merge it.
> 
> If anyone volunteers to test this locally upfront by replacing source files let me know. I'll then share the details

I’ll happily test it out 👍

**Comment by N3rdix** [comment]
just download the changed [audi_api.py](https://github.com/audiconnect/audi_connect_ha/blob/a81f1e786cfc0a89191acd678b2070e02d088a17/custom_components/audiconnect/audi_api.py) from the PR and overwrite the existing file in your custom_components folder. After a HA restart it should work as usual.

**Comment by florie1706** [comment]
> I found the issue 🥳 I will submit a PR this evening and hopefully someone can merge it.
> 
> If anyone volunteers to test this locally upfront by replacing source files let me know. I'll then share the details

Works again :) thx

**Comment by eskholm** [comment]
> just download the changed [audi_api.py](https://github.com/audiconnect/audi_connect_ha/blob/a81f1e786cfc0a89191acd678b2070e02d088a17/custom_components/audiconnect/audi_api.py) from the PR #489 and overwrite the existing file in your custom_components folder. After a HA restart it should work as usual.

Confirmed working! Thank you!

**Comment by iz3man** [comment]
Here the problem still exists. I removed the custom_component, restarted HA, reinstalled 1.13.1, restarted, but I still get "invalid credentials". It was working some days ago, then I had to re-setup my car form scratch, and I guess this was what cause the integration to stop working. 
Any ideas how to proceed?
