### ISSUE TITLE
charging rate doesn't make sense

### ISSUE THREAD

**Issue by jtonk** [audiconnect/audi_connect_ha#60]
The charging rate km/hour doesn't make any sense.

![image](https://user-images.githubusercontent.com/731526/103657681-7bf95e80-4f6a-11eb-94cc-de50997beea5.png)

Audi does not publish the charging rate number in the app or website anymore, so maybe it is not maintained in their API.

The charging power is still correct.

**Comment by fhloston** [comment]
Interesting, i do not see the charging power in my setup at all - has this been removed now?

**Comment by coreywillwhat** [comment]
charging rate is still published in the API.
km/h makes sense if you think of KM of distance you can drive are being added to the vehicle battery.

If you disagree or want think this should be something different. Please let me know. This issues is 3 years stale, so closing this.
