### ISSUE TITLE
Connection Seems to Go Stale - Times out?

### ISSUE THREAD

**Issue by shuntfield** [audiconnect/audi_connect_ha#81]
Hi Everyone, 

Are you noticing that the connection seems to go stale? By this I mean, if you haven't restarted HA or done anything major for a few days, the connection to Audi seems to go stale, and nothing updates.

Then when you reload the integration, or increasingly I am having to remove the integration and reload it after a restart it seems to correct itself again. I love this integration but it makes it unreliable. Is there a token that is timing out? Is there anyway to check?

Thoughts welcomed if anyone else is experiencing this or if there is a workaround/fix?

Shunts...

**Comment by fhloston** [comment]
same here

**Comment by thorsten** [comment]
I have a similar issue, some values are updated, some not. For example, my state of charge is correct, my range is not although both values are updated for the same time.

**Comment by shuntfield** [comment]
I find oil level and location is perhaps the most regular of the ones that fail.

**Comment by coreywillwhat** [comment]
@shuntfield can we close this one?

**Comment by shuntfield** [comment]
On the latest version it's not working again for me.

I have done a few refreshes vehicle and cloud and it's not working again will need to revert and try again.

**Comment by shuntfield** [comment]
I'll try a go back to an older version which might resolve it.
I have changed state_of_charge to a Battery Class on mine so it will revert the changes I have made

**Comment by shuntfield** [comment]
Sorry was confused with something else.
It works now 😁

**Comment by shuntfield** [comment]
👏🏻

**Comment by coreywillwhat** [comment]
Thank you!
