### ISSUE TITLE
myaudi destination feature

### ISSUE THREAD

**Issue by pilot1981** [audiconnect/audi_connect_ha#85]
Hi,
will be great to insert new destination in myaudi destination using your component: you think this could be possible in the feature?

**Comment by webmatrixxxl** [comment]
I'm asking the same. Will it be possible to send a destination to Audi MMI?

**Comment by webmatrixxxl** [comment]
I mean is it possible somehow to send programmatically destination through the API not necessary by HА?

**Comment by coreywillwhat** [comment]
Closing this issue as its nearly 2 years old. I dont believe this functionality is available in audi API anymore if ever. Please open a new issue if this becomes available in the Audi App.
