### ISSUE TITLE
AdBlue & Lock

### ISSUE THREAD

**Issue by riki81** [audiconnect/audi_connect_ha#90]
Hi! I've got 2 questions.

ADBLUE
On official MyAudi App I can see the level of AdBlue (diesel engines only).
Here I don't see that entity.
Is it possible to add it in future?

LOCK/UNLOCK
It sounds strange, but it seems not to be aligned to the real status present on MyAudi.
It continues to present the doors as unlocked, if unlock and lock again.
Is it forced a sort of refresh, every X seconds? Doors can be opened from 3 different devices: original remote/key, MyAudi app, this add-on, so it's important to check often the REAL status.

Someone could help me?

Thank you!

**Comment by coreywillwhat** [comment]
Adblue should be available for diesel cars.
No recent reports of lock/unlock not being up to speed.
Closing. Please open a new issue if a problem arrises.
