### ISSUE TITLE
Special username format in CN

### ISSUE THREAD

**Issue by terry-fang** [audiconnect/audi_connect_ha#92]
Hello, the user name used in China is an eleven-digit phone number, like 12345678912. Logging in using email is not an option here.

Another notice that possibly useful is that they (perhaps) use different server than EU or US. Because rather than the standard MyAudi application, we use a different version which is only available in the Chinese App Store.

Thanks for your work!

**Comment by casdr** [comment]
@terry-fang see https://github.com/arjenvrh/audi_connect_ha/issues/153#issuecomment-1598867778

**Comment by cdnninja** [comment]
Lets track this in #96
