### ISSUE TITLE
support_preheater set to False: 502

### ISSUE THREAD

**Issue by rklomp** [audiconnect/audi_connect_ha#97]
Received below error with latest version of the integration. 

Log Details

Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:557
Integration: Audi Connect
First occurred: 19:44:53 (1 occurrences)
Last logged: 19:44:53
support_preheater set to False: 502

**Comment by Virusburn** [comment]
I have similar problems: 

![grafik](https://user-images.githubusercontent.com/77741043/145004023-336634a7-1a58-4e7c-9f38-cb6e5b1ad0ac.png)

1.
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:520
Integration: Audi Connect
First occurred: 10:09:19 (1 occurrences)
Last logged: 10:09:19
support_climater set to False: 403

2.
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:637
Integration: Audi Connect
First occurred: 10:09:19 (1 occurrences)
Last logged: 10:09:19
support_charger set to False: 403

3.
Logger: custom_components.audiconnect.audi_connect_account
Source: custom_components/audiconnect/audi_connect_account.py:557
Integration: Audi Connect
First occurred: 10:09:19 (1 occurrences)
Last logged: 10:09:19
support_preheater set to False: 502

**Comment by N3rdix** [comment]
My car does have a charger as it is a Q4 (BEV) and I receive exactly the same 3 errors...

**Comment by driouch90** [comment]
I also get the same problem for audi Q4 E-tron

**Comment by driouch90** [comment]
![92F776E9-6655-4127-99BA-C0C3D90D45B1](https://user-images.githubusercontent.com/56792951/147827182-c5d535d2-9a3d-410f-bc1b-21f2d2c63079.jpeg)
- I also get the same problem for audi Q4 E-tron

**Comment by MartinHannemann** [comment]
Same problem with my Audi e-tron GT

**Comment by thorsten** [comment]
Same problem with my Audi e-tron

**Comment by t0bias-r** [comment]
During start-up, the code tries to query information of all implemented modules (modules are: status_report, position, climater, preheater, charger). [in `AudiConnectVehicle::__init__` all vars are set to `True`]
If a query fails, the support for that module will be disabled and no further query will be executed.
In that case, the `support_<module> set to False` message is shown.

What I have noticed is, that from time to time, the Audi servers return an error although the module is available.
I guess, that a restart is required to re-enable the support.

**Comment by N3rdix** [comment]
A restart doesn’t help in my case, it’s always setting the modules to False, it never worked for my Q4 although the functions are available on myAudi

**Comment by MartinHannemann** [comment]
The problem might be how EVs are registering with the API, they don't have preheater, but have climate control. Is preheater a prereq for climate control somewhere in the code?

In my audi app I can control climate and the lock, but with this extension I can only control the lock.

**Comment by stuvat** [comment]
I get the same error, and only get to controll Lock/unlock in HA.

**Comment by bababaram** [comment]
Likewise, I get this heater error, only control options are lock/unlock in homeassistant.

**Comment by SchwarzAxel** [comment]
Hi! I am still facing this issue with the latest code and my Audi A6 Hybrid. Anz ideas how to fix this?

**Comment by N3rdix** [comment]
> Hi! I am still facing this issue with the latest code and my Audi A6 Hybrid. Anz ideas how to fix this?

Still the same errors for my Q4, also running the latest version. I wonder if this can fixed as well

**Comment by MartinHannemann** [comment]
I'm willing to pay a small fee to have this sorted, its really annoying that I cant control the climate using this extension. What would it take to have it fixed? @arjenvrh

**Comment by gllmlbrt** [comment]
Same issue here on Q3 TFSI e 2023

**Comment by jorishaverkort** [comment]
Issue still remains, Etron 55.
As mentioned above. Happy also to pay someone a small fee to fix it

**Comment by t0bias-r** [comment]
@jorishaverkort See PR https://github.com/arjenvrh/audi_connect_ha/pull/188

**Comment by coreywillwhat** [comment]
Are these errors still present with latest versions?

**Comment by bababaram** [comment]
Hi,

Fixed for me!

Great work
________________________________

**Comment by coreywillwhat** [comment]
Closing this issue. Please resubmit an issue if any issues persist
