### ISSUE TITLE
sensor.audi_e_tron_charging_power only updates on restart

### ISSUE THREAD

**Issue by jtonk** [audiconnect/audi_connect_ha#98]
When I start charging the car, HA won't update the status of sensor.audi_e_tron_charging_power. However, when I restart HA (and the car is already charging), the value updates.

Is anybody experiencing the same issue?

**Comment by derhappy** [comment]
I don't even have a charging_power sensor. I think you're right, there was one at some point. State is working fine though:
![grafik](https://user-images.githubusercontent.com/61394775/145467523-56fc9004-e3fd-4e9f-b82d-938fd23d0df4.png)

**Comment by jtonk** [comment]
So you don't even have the sensor. Mine is working but, doesn't update w/o restart of HA

<img width="336" alt="Screenshot 2021-12-09 at 21 21 59" src="https://user-images.githubusercontent.com/731526/145470791-0cba545c-f781-4218-9e64-1704ac2fd520.png">

**Comment by coreywillwhat** [comment]
A cloud pull is now conducted after an action is completed, weather the `refresh vehicle data` completes or not. This should resolve the update issue. 

This issue is over 2 years old. Closing. Please resubmit an issue if your issues persist.
